# started from example at http://blog.azerg.com/using-travis-yml-with-cmake-project/
language: cpp
compiler:
  - gcc
# Use container architecture so maybe we could cache some outputs
sudo: false
# Need trusty to get osg 3.2; I'm not supporting osg 3.0 at the moment
dist: trusty
# Use APT feature to avoid needing sudo for dependencies
addons:
  apt:
    packages:
      - libboost-python-dev
      - openscenegraph
      - libopenscenegraph-dev
# Build each OSG module in a separate job, to reduce risk of timeout
# TODO: slowest modules first, like backpack algorithm
env:
  - OSG_MODULE=_osgUtil
  - OSG_MODULE=_osgAnimation
  - OSG_MODULE=_osgDB
  - OSG_MODULE=_osgParticle
  - OSG_MODULE=_osgGA
  - OSG_MODULE=_osgManipulator
  - OSG_MODULE=_osgSim
  - OSG_MODULE=_osgText
  - OSG_MODULE=_osgViewer
  - OSG_MODULE=_osgVolume
  - OSG_MODULE=_osgWidget
  - OSG_MODULE=_osgFX
# TODO: add giant time consuming _osg module
before_script:
  - mkdir build_cmake
  - cd build_cmake
  - cmake ..
# Use -j4 to maybe speed up compilation
script:
  - make -j4 $OSG_MODULE

