# started from example at http://blog.azerg.com/using-travis-yml-with-cmake-project/
language: cpp
compiler:
  - gcc
sudo: required
# Need trusty to get osg 3.2; I'm not supporting osg 3.0 at the moment
dist: trusty
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-python-dev
  - sudo apt-get install -y libopenscenegraph-dev
  - mkdir build_cmake
  - cd build_cmake
  - cmake ..
script:
  - make
