# started from example at http://blog.azerg.com/using-travis-yml-with-cmake-project/
language: cpp
compiler:
  - gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-python-dev
  - sudo apt-get install -y openscenegraph
  - mkdir build_cmake
  - cd build_cmake
  - cmake ..
script:
  - make
