# started from example at http://blog.azerg.com/using-travis-yml-with-cmake-project/
language: cpp
compiler:
  - gcc
# TODO: Use container architecture so maybe we could cache some outputs
# But not yet, because container arch does not seem to have Trusty dist. Nov 30 2015
sudo: false
# Need trusty to get osg 3.2; I'm not supporting osg 3.0 at the moment
dist: trusty
# Use APT feature to avoid needing sudo for dependencies
addons:
  apt:
    packages:
      - libboost-python-dev
      - openscenegraph
      - libopenscenegraph-dev
# Build each OSG module in a separate job, to reduce risk of timeout
# Run slowest modules first, like backpack algorithm
env:
  - OSG_MODULE=_osg
  - OSG_MODULE=_osgUtil
  - OSG_MODULE=_osgAnimation
  - OSG_MODULE=_osgDB
  - OSG_MODULE=_osgParticle
  - OSG_MODULE=_osgGA
  - OSG_MODULE=_osgManipulator
  - OSG_MODULE=_osgSim
  - OSG_MODULE=_osgText
  - OSG_MODULE=_osgViewer
  - OSG_MODULE=_osgVolume
  - OSG_MODULE=_osgWidget
  - OSG_MODULE=_osgFX
before_script:
  - mkdir build_cmake
  - cd build_cmake
  - cmake ..
# Use -j4 to maybe speed up compilation
script:
  - make -j4 $OSG_MODULE

