// This file has been generated by Py++.

#include "boost/python.hpp"
#include "indexing_suite/container_suite.hpp"
#include "indexing_suite/map.hpp"
#include "wrap_osgDB.h"
#include "_ref_ptr_less__osgDB_scope_BaseCompressor__greater___value_traits.pypp.hpp"
#include "CompressorMap.pypp.hpp"

namespace bp = boost::python;

void register_CompressorMap_class(){

    { //::std::map< std::string, osg::ref_ptr<osgDB::BaseCompressor> >
        typedef bp::class_< std::map< std::string, osg::ref_ptr<osgDB::BaseCompressor> > > CompressorMap_exposer_t;
        CompressorMap_exposer_t CompressorMap_exposer = CompressorMap_exposer_t( "CompressorMap" );
        bp::scope CompressorMap_scope( CompressorMap_exposer );
        CompressorMap_exposer.def( bp::indexing::map_suite< std::map< std::string, osg::ref_ptr<osgDB::BaseCompressor> > >() );
    }

}
