// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osgDB.h"
#include "FileNameComparator.pypp.hpp"

namespace bp = boost::python;

void register_FileNameComparator_class(){

    bp::class_< osgDB::FileNameComparator >( "FileNameComparator" )    
        .def( 
            "__call__"
            , (bool ( ::osgDB::FileNameComparator::* )( ::std::string const &,::std::string const & ) const)( &::osgDB::FileNameComparator::operator() )
            , ( bp::arg("lhs"), bp::arg("rhs") ) );

}
