// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osgDB.h"
#include "RegisterWrapperProxy.pypp.hpp"

namespace bp = boost::python;

void register_RegisterWrapperProxy_class(){

    bp::class_< osgDB::RegisterWrapperProxy >( "RegisterWrapperProxy", bp::no_init );

}
