// This file has been generated by Py++.

#include "boost/python.hpp"

#include "__call_policies.pypp.hpp"

#include "__convenience.pypp.hpp"

#include "indexing_suite/container_suite.hpp"

#include "indexing_suite/vector.hpp"

#include "wrap_osgVolume.h"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/AlphaFuncProperty.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/CollectPropertiesVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/CompositeLayer.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/CompositeProperty.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/FixedFunctionTechnique.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/ImageDetails.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/ImageLayer.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/IsoSurfaceProperty.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/Layer.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/LightingProperty.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/Locator.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/LocatorCallbacks.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/MaximumIntensityProjectionProperty.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/Property.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/PropertyAdjustmentCallback.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/PropertyVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/RayTracedTechnique.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/SampleDensityProperty.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/SampleDensityWhenMovingProperty.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/ScalarProperty.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/SwitchProperty.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/TileID.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/TransferFunctionProperty.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/TransparencyProperty.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/Volume.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/VolumeTechnique.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/VolumeTile.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgVolume/generated_code/_osgVolume_free_functions.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(_osgVolume){
    register_LocatorCallbacks_class();

    register_Property_class();

    register_ScalarProperty_class();

    register_AlphaFuncProperty_class();

    register_PropertyVisitor_class();

    register_CollectPropertiesVisitor_class();

    register_Layer_class();

    register_CompositeLayer_class();

    register_CompositeProperty_class();

    register_VolumeTechnique_class();

    register_FixedFunctionTechnique_class();

    register_ImageDetails_class();

    register_ImageLayer_class();

    register_IsoSurfaceProperty_class();

    register_LightingProperty_class();

    register_Locator_class();

    register_MaximumIntensityProjectionProperty_class();

    register_PropertyAdjustmentCallback_class();

    register_RayTracedTechnique_class();

    register_SampleDensityProperty_class();

    register_SampleDensityWhenMovingProperty_class();

    register_SwitchProperty_class();

    register_TileID_class();

    register_TransferFunctionProperty_class();

    register_TransparencyProperty_class();

    register_Volume_class();

    register_VolumeTile_class();

    register_free_functions();
}

