// This file has been generated by Py++.

#include "boost/python.hpp"

#include "__call_policies.pypp.hpp"

#include "__convenience.pypp.hpp"

#include "indexing_suite/value_traits.hpp"

#include "indexing_suite/container_suite.hpp"

#include "indexing_suite/vector.hpp"

#include "indexing_suite/list.hpp"

#include "wrap_osgManipulator.h"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/AntiSquish.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/CommandManager.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/CompositeDragger.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/Constraint.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/Constraints.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/CylinderPlaneProjector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/CylinderProjector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/Dragger.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/DraggerCallback.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/DraggerTransformCallback.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/GridConstraint.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/IntersectionList.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/LineProjector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/MotionCommand.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/PlaneProjector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/PointerInfo.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/Projector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/Rotate3DCommand.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/RotateCylinderDragger.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/RotateSphereDragger.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/Scale1DCommand.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/Scale1DDragger.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/Scale2DCommand.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/Scale2DDragger.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/ScaleAxisDragger.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/ScaleUniformCommand.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/Selections.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/SpherePlaneProjector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/SphereProjector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/TabBoxDragger.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/TabBoxTrackballDragger.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/TabPlaneDragger.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/TabPlaneTrackballDragger.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/TrackballDragger.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/Translate1DDragger.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/Translate2DDragger.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/TranslateAxisDragger.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/TranslateInLineCommand.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/TranslateInPlaneCommand.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/TranslatePlaneDragger.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/_osgManipulator_free_functions.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/_osgManipulator_global_variables.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgManipulator/generated_code/vector_less__osg_scope_ref_ptr_less_osgManipulator_scope_DraggerCallback_greater___greater_.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(_osgManipulator){
    register_vector_less__osg_scope_ref_ptr_less_osgManipulator_scope_DraggerCallback_greater___greater__class();

    register_Constraints_class();

    register_IntersectionList_class();

    register_Selections_class();

    register_AntiSquish_class();

    register_CommandManager_class();

    register_Dragger_class();

    register_CompositeDragger_class();

    register_Constraint_class();

    register_Projector_class();

    register_CylinderProjector_class();

    register_CylinderPlaneProjector_class();

    register_DraggerCallback_class();

    register_DraggerTransformCallback_class();

    register_GridConstraint_class();

    register_LineProjector_class();

    register_MotionCommand_class();

    register_PlaneProjector_class();

    register_PointerInfo_class();

    register_Rotate3DCommand_class();

    register_RotateCylinderDragger_class();

    register_RotateSphereDragger_class();

    register_Scale1DCommand_class();

    register_Scale1DDragger_class();

    register_Scale2DCommand_class();

    register_Scale2DDragger_class();

    register_ScaleAxisDragger_class();

    register_ScaleUniformCommand_class();

    register_SphereProjector_class();

    register_SpherePlaneProjector_class();

    register_TabBoxDragger_class();

    register_TabBoxTrackballDragger_class();

    register_TabPlaneDragger_class();

    register_TabPlaneTrackballDragger_class();

    register_TrackballDragger_class();

    register_Translate1DDragger_class();

    register_Translate2DDragger_class();

    register_TranslateAxisDragger_class();

    register_TranslateInLineCommand_class();

    register_TranslateInPlaneCommand_class();

    register_TranslatePlaneDragger_class();

    register_global_variables();

    register_free_functions();
}

