// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osgAnimation.h"
#include "InQuadFunction.pypp.hpp"

namespace bp = boost::python;

void register_InQuadFunction_class(){

    bp::class_< osgAnimation::InQuadFunction >( "InQuadFunction" )    
        .def( 
            "getValueAt"
            , (void (*)( float,float & ))( &::osgAnimation::InQuadFunction::getValueAt )
            , ( bp::arg("t"), bp::arg("result") ) )    
        .staticmethod( "getValueAt" );

}
