// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osgAnimation.h"
#include "Keyframe.pypp.hpp"

namespace bp = boost::python;

void register_Keyframe_class(){

    bp::class_< osgAnimation::Keyframe >( "Keyframe" )    
        .def( 
            "getTime"
            , (double ( ::osgAnimation::Keyframe::* )(  ) const)( &::osgAnimation::Keyframe::getTime ) )    
        .def( 
            "setTime"
            , (void ( ::osgAnimation::Keyframe::* )( double ) )( &::osgAnimation::Keyframe::setTime )
            , ( bp::arg("time") ) );

}
