// This file has been generated by Py++.

#ifndef MotionList_hpp__pyplusplus_wrapper
#define MotionList_hpp__pyplusplus_wrapper

void register_MotionList_class();

#endif//MotionList_hpp__pyplusplus_wrapper
