// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osgAnimation.h"
#include "wrap_referenced.h"
#include "Target.pypp.hpp"

namespace bp = boost::python;

void register_Target_class(){

    bp::class_< osgAnimation::Target, bp::bases< ::osg::Referenced >, osg::ref_ptr< ::osgAnimation::Target >, boost::noncopyable >( "Target", bp::init< >() )    
        .def( 
            "getCount"
            , (int ( ::osgAnimation::Target::* )(  ) const)( &::osgAnimation::Target::getCount ) )    
        .def( 
            "getWeight"
            , (float ( ::osgAnimation::Target::* )(  ) const)( &::osgAnimation::Target::getWeight ) )    
        .def( 
            "reset"
            , (void ( ::osgAnimation::Target::* )(  ) )( &::osgAnimation::Target::reset ) );

}
