// This file has been generated by Py++.

#include "boost/python.hpp"

#include "__call_policies.pypp.hpp"

#include "__convenience.pypp.hpp"

#include "__array_1.pypp.hpp"

#include "indexing_suite/value_traits.hpp"

#include "indexing_suite/container_suite.hpp"

#include "indexing_suite/vector.hpp"

#include "indexing_suite/set.hpp"

#include "indexing_suite/map.hpp"

#include "indexing_suite/list.hpp"

#include "wrap_osgUtil.h"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/AddRangeOperator.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/BaseOptimizerVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/CompileOps.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/CompileSets.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/ContextSet.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/CubeMapGenerator.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/CullVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/DelaunayConstraint.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/DelaunayTriangulator.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/DisplayRequirementsVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/DrawElementTypeSimplifier.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/DrawElementTypeSimplifierVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/EdgeCollector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/EdgeList.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/EdgeSet.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/GLObjectsOperation.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/GLObjectsVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/GeodesToDivideList.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/GeometryCollector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/GeometryList.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/HalfWayMapGenerator.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/HighlightMapGenerator.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/Hit.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/IncrementalCompileOperation.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/IndexMeshVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/IntersectVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/IntersectionVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/Intersector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/IntersectorGroup.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/Intersectors.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/LessDepthSortFunctor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/LineSegmentHitListMap.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/LineSegmentIntersector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/MultiplyRangeOperator.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/Optimizer.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/PerlinNoise.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/PickVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/PlaneIntersections.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/PlaneIntersector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/PointList.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/PointSet.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/PolytopeIntersections.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/PolytopeIntersector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/PositionalStateContainer.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/PrimList.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/PrimitiveValueMap.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/PrintVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/ProgramSet.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/ReflectionMapGenerator.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/RenderBin.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/RenderBinList.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/RenderLeaf.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/RenderLeafList.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/RenderStage.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/ReversePrimitiveFunctor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/SceneGraphBuilder.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/SceneView.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/ShaderGenCache.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/ShaderGenVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/Simplifier.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/SmoothingVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/StateGraph.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/StateGraphList.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/StateToCompile.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/Statistics.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/StatsVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/TangentSpaceGenerator.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/Tessellator.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/TexUnitAttrMatrixListMap.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/TextureSet.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/TransformAttributeFunctor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/TransformCallback.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/TriStripVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/TriangleSet.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/UpdateVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/VecList.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/VertexAccessOrderVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/VertexCacheMissVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/VertexCacheVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/_osgUtil_free_functions.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/_osgUtil_global_variables.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/dereference_clear.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/dereference_less.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/list_less__osg_scope_ref_ptr_less_osgUtil_scope_EdgeCollector_scope_Edgeloop_greater___greater_.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/set_less__osg_scope_Drawable_ptr___greater_.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/set_less__osg_scope_Group_ptr___greater_.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/set_less__osg_scope_Node_ptr___greater_.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/set_less__osg_scope_StateSet_ptr___greater_.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/std_list_tiarray_uint_5125.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/std_vector_pair_StateAttribute_RefMatrixd.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/vector_less__int__greater_.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/vector_less__osgUtil_scope_Hit__greater_.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgUtil/generated_code/vector_less__osg_scope_ref_ptr_less_osgUtil_scope_RenderLeaf_greater___greater_.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(_osgUtil){
    register_std_vector_pair_StateAttribute_RefMatrixd_class();

    register_StateGraphList_class();

    register_RenderLeafList_class();

    register_PlaneIntersections_class();

    register_vector_less__osgUtil_scope_Hit__greater__class();

    register_PrimList_class();

    register_vector_less__osg_scope_ref_ptr_less_osgUtil_scope_RenderLeaf_greater___greater__class();

    register_Intersectors_class();

    register_PointList_class();

    register_EdgeList_class();

    register_VecList_class();

    register_vector_less__int__greater__class();

    register_PolytopeIntersections_class();

    register_TriangleSet_class();

    register_PointSet_class();

    register_EdgeSet_class();

    register_TextureSet_class();

    register_set_less__osg_scope_StateSet_ptr___greater__class();

    register_ProgramSet_class();

    register_set_less__osg_scope_Node_ptr___greater__class();

    register_set_less__osg_scope_Group_ptr___greater__class();

    register_ContextSet_class();

    register_GeometryList_class();

    register_GeodesToDivideList_class();

    register_set_less__osg_scope_Drawable_ptr___greater__class();

    register_TexUnitAttrMatrixListMap_class();

    register_PrimitiveValueMap_class();

    register_LineSegmentHitListMap_class();

    register_RenderBinList_class();

    register_CompileSets_class();

    register_CompileOps_class();

    register_list_less__osg_scope_ref_ptr_less_osgUtil_scope_EdgeCollector_scope_Edgeloop_greater___greater__class();

    register_std_list_tiarray_uint_5125_class();

    register_AddRangeOperator_class();

    register_BaseOptimizerVisitor_class();

    register_CubeMapGenerator_class();

    register_CullVisitor_class();

    register_DelaunayConstraint_class();

    register_DelaunayTriangulator_class();

    register_DisplayRequirementsVisitor_class();

    register_DrawElementTypeSimplifier_class();

    register_DrawElementTypeSimplifierVisitor_class();

    register_EdgeCollector_class();

    register_GLObjectsOperation_class();

    register_GLObjectsVisitor_class();

    register_Optimizer_class();

    register_GeometryCollector_class();

    register_HalfWayMapGenerator_class();

    register_HighlightMapGenerator_class();

    register_Hit_class();

    register_IncrementalCompileOperation_class();

    register_IndexMeshVisitor_class();

    register_IntersectVisitor_class();

    register_Intersector_class();

    register_IntersectionVisitor_class();

    register_IntersectorGroup_class();

    register_LessDepthSortFunctor_class();

    register_LineSegmentIntersector_class();

    register_MultiplyRangeOperator_class();

    register_PerlinNoise_class();

    register_PickVisitor_class();

    register_PlaneIntersector_class();

    register_PolytopeIntersector_class();

    register_PositionalStateContainer_class();

    register_PrintVisitor_class();

    register_ReflectionMapGenerator_class();

    register_RenderBin_class();

    register_RenderLeaf_class();

    register_RenderStage_class();

    register_ReversePrimitiveFunctor_class();

    register_SceneGraphBuilder_class();

    register_SceneView_class();

    register_ShaderGenCache_class();

    register_ShaderGenVisitor_class();

    register_Simplifier_class();

    register_SmoothingVisitor_class();

    register_StateGraph_class();

    register_StateToCompile_class();

    register_Statistics_class();

    register_StatsVisitor_class();

    register_TangentSpaceGenerator_class();

    register_Tessellator_class();

    register_TransformAttributeFunctor_class();

    register_TransformCallback_class();

    register_TriStripVisitor_class();

    register_UpdateVisitor_class();

    register_VertexAccessOrderVisitor_class();

    register_VertexCacheMissVisitor_class();

    register_VertexCacheVisitor_class();

    register_dereference_clear_class();

    register_dereference_less_class();

    register_global_variables();

    register_free_functions();
}

