// This file has been generated by Py++.

#include "boost/python.hpp"

#include "__call_policies.pypp.hpp"

#include "__convenience.pypp.hpp"

#include "__array_1.pypp.hpp"

#include "indexing_suite/value_traits.hpp"

#include "indexing_suite/container_suite.hpp"

#include "indexing_suite/vector.hpp"

#include "indexing_suite/set.hpp"

#include "indexing_suite/map.hpp"

#include "indexing_suite/list.hpp"

#include "wrap_osgUtil.h"

#include "AddRangeOperator.pypp.hpp"

#include "BaseOptimizerVisitor.pypp.hpp"

#include "CompileOps.pypp.hpp"

#include "CompileSets.pypp.hpp"

#include "ContextSet.pypp.hpp"

#include "CubeMapGenerator.pypp.hpp"

#include "CullVisitor.pypp.hpp"

#include "DelaunayConstraint.pypp.hpp"

#include "DelaunayTriangulator.pypp.hpp"

#include "DisplayRequirementsVisitor.pypp.hpp"

#include "DrawElementTypeSimplifier.pypp.hpp"

#include "DrawElementTypeSimplifierVisitor.pypp.hpp"

#include "EdgeCollector.pypp.hpp"

#include "EdgeList.pypp.hpp"

#include "EdgeSet.pypp.hpp"

#include "GLObjectsOperation.pypp.hpp"

#include "GLObjectsVisitor.pypp.hpp"

#include "GeodesToDivideList.pypp.hpp"

#include "GeometryCollector.pypp.hpp"

#include "GeometryList.pypp.hpp"

#include "HalfWayMapGenerator.pypp.hpp"

#include "HighlightMapGenerator.pypp.hpp"

#include "Hit.pypp.hpp"

#include "IncrementalCompileOperation.pypp.hpp"

#include "IndexMeshVisitor.pypp.hpp"

#include "IntersectVisitor.pypp.hpp"

#include "IntersectionVisitor.pypp.hpp"

#include "Intersector.pypp.hpp"

#include "IntersectorGroup.pypp.hpp"

#include "Intersectors.pypp.hpp"

#include "LessDepthSortFunctor.pypp.hpp"

#include "LineSegmentHitListMap.pypp.hpp"

#include "LineSegmentIntersector.pypp.hpp"

#include "MultiplyRangeOperator.pypp.hpp"

#include "Optimizer.pypp.hpp"

#include "PerlinNoise.pypp.hpp"

#include "PickVisitor.pypp.hpp"

#include "PlaneIntersections.pypp.hpp"

#include "PlaneIntersector.pypp.hpp"

#include "PointList.pypp.hpp"

#include "PointSet.pypp.hpp"

#include "PolytopeIntersections.pypp.hpp"

#include "PolytopeIntersector.pypp.hpp"

#include "PositionalStateContainer.pypp.hpp"

#include "PrimList.pypp.hpp"

#include "PrimitiveValueMap.pypp.hpp"

#include "PrintVisitor.pypp.hpp"

#include "ProgramSet.pypp.hpp"

#include "ReflectionMapGenerator.pypp.hpp"

#include "RenderBin.pypp.hpp"

#include "RenderBinList.pypp.hpp"

#include "RenderLeaf.pypp.hpp"

#include "RenderLeafList.pypp.hpp"

#include "RenderStage.pypp.hpp"

#include "ReversePrimitiveFunctor.pypp.hpp"

#include "SceneGraphBuilder.pypp.hpp"

#include "SceneView.pypp.hpp"

#include "ShaderGenCache.pypp.hpp"

#include "ShaderGenVisitor.pypp.hpp"

#include "Simplifier.pypp.hpp"

#include "SmoothingVisitor.pypp.hpp"

#include "StateGraph.pypp.hpp"

#include "StateGraphList.pypp.hpp"

#include "StateToCompile.pypp.hpp"

#include "Statistics.pypp.hpp"

#include "StatsVisitor.pypp.hpp"

#include "TangentSpaceGenerator.pypp.hpp"

#include "Tessellator.pypp.hpp"

#include "TexUnitAttrMatrixListMap.pypp.hpp"

#include "TextureSet.pypp.hpp"

#include "TransformAttributeFunctor.pypp.hpp"

#include "TransformCallback.pypp.hpp"

#include "TriStripVisitor.pypp.hpp"

#include "TriangleSet.pypp.hpp"

#include "UpdateVisitor.pypp.hpp"

#include "VecList.pypp.hpp"

#include "VertexAccessOrderVisitor.pypp.hpp"

#include "VertexCacheMissVisitor.pypp.hpp"

#include "VertexCacheVisitor.pypp.hpp"

#include "_osgUtil_free_functions.pypp.hpp"

#include "_osgUtil_global_variables.pypp.hpp"

#include "dereference_clear.pypp.hpp"

#include "dereference_less.pypp.hpp"

#include "list_less__osg_scope_ref_ptr_less_osgUtil_scope_EdgeCollector_scope_Edgeloop_greater___greater_.pypp.hpp"

#include "set_less__osg_scope_Drawable_ptr___greater_.pypp.hpp"

#include "set_less__osg_scope_Group_ptr___greater_.pypp.hpp"

#include "set_less__osg_scope_Node_ptr___greater_.pypp.hpp"

#include "set_less__osg_scope_StateSet_ptr___greater_.pypp.hpp"

#include "std_list_tiarray_uint_5125.pypp.hpp"

#include "std_vector_pair_StateAttribute_RefMatrixd.pypp.hpp"

#include "vector_less__int__greater_.pypp.hpp"

#include "vector_less__osgUtil_scope_Hit__greater_.pypp.hpp"

#include "vector_less__osg_scope_ref_ptr_less_osgUtil_scope_RenderLeaf_greater___greater_.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(_osgUtil){
    register_std_vector_pair_StateAttribute_RefMatrixd_class();

    register_StateGraphList_class();

    register_RenderLeafList_class();

    register_PlaneIntersections_class();

    register_vector_less__osgUtil_scope_Hit__greater__class();

    register_PrimList_class();

    register_vector_less__osg_scope_ref_ptr_less_osgUtil_scope_RenderLeaf_greater___greater__class();

    register_Intersectors_class();

    register_PointList_class();

    register_EdgeList_class();

    register_VecList_class();

    register_vector_less__int__greater__class();

    register_PolytopeIntersections_class();

    register_TriangleSet_class();

    register_PointSet_class();

    register_EdgeSet_class();

    register_TextureSet_class();

    register_set_less__osg_scope_StateSet_ptr___greater__class();

    register_ProgramSet_class();

    register_set_less__osg_scope_Node_ptr___greater__class();

    register_set_less__osg_scope_Group_ptr___greater__class();

    register_ContextSet_class();

    register_GeometryList_class();

    register_GeodesToDivideList_class();

    register_set_less__osg_scope_Drawable_ptr___greater__class();

    register_TexUnitAttrMatrixListMap_class();

    register_PrimitiveValueMap_class();

    register_LineSegmentHitListMap_class();

    register_RenderBinList_class();

    register_CompileSets_class();

    register_CompileOps_class();

    register_list_less__osg_scope_ref_ptr_less_osgUtil_scope_EdgeCollector_scope_Edgeloop_greater___greater__class();

    register_std_list_tiarray_uint_5125_class();

    register_AddRangeOperator_class();

    register_BaseOptimizerVisitor_class();

    register_CubeMapGenerator_class();

    register_CullVisitor_class();

    register_DelaunayConstraint_class();

    register_DelaunayTriangulator_class();

    register_DisplayRequirementsVisitor_class();

    register_DrawElementTypeSimplifier_class();

    register_DrawElementTypeSimplifierVisitor_class();

    register_EdgeCollector_class();

    register_GLObjectsOperation_class();

    register_GLObjectsVisitor_class();

    register_Optimizer_class();

    register_GeometryCollector_class();

    register_HalfWayMapGenerator_class();

    register_HighlightMapGenerator_class();

    register_Hit_class();

    register_IncrementalCompileOperation_class();

    register_IndexMeshVisitor_class();

    register_IntersectVisitor_class();

    register_Intersector_class();

    register_IntersectionVisitor_class();

    register_IntersectorGroup_class();

    register_LessDepthSortFunctor_class();

    register_LineSegmentIntersector_class();

    register_MultiplyRangeOperator_class();

    register_PerlinNoise_class();

    register_PickVisitor_class();

    register_PlaneIntersector_class();

    register_PolytopeIntersector_class();

    register_PositionalStateContainer_class();

    register_PrintVisitor_class();

    register_ReflectionMapGenerator_class();

    register_RenderBin_class();

    register_RenderLeaf_class();

    register_RenderStage_class();

    register_ReversePrimitiveFunctor_class();

    register_SceneGraphBuilder_class();

    register_SceneView_class();

    register_ShaderGenCache_class();

    register_ShaderGenVisitor_class();

    register_Simplifier_class();

    register_SmoothingVisitor_class();

    register_StateGraph_class();

    register_StateToCompile_class();

    register_Statistics_class();

    register_StatsVisitor_class();

    register_TangentSpaceGenerator_class();

    register_Tessellator_class();

    register_TransformAttributeFunctor_class();

    register_TransformCallback_class();

    register_TriStripVisitor_class();

    register_UpdateVisitor_class();

    register_VertexAccessOrderVisitor_class();

    register_VertexCacheMissVisitor_class();

    register_VertexCacheVisitor_class();

    register_dereference_clear_class();

    register_dereference_less_class();

    register_global_variables();

    register_free_functions();
}

