// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osgUtil.h"
#include "wrap_referenced.h"
#include "HalfWayMapGenerator.pypp.hpp"

namespace bp = boost::python;

void register_HalfWayMapGenerator_class(){

    { //::osgUtil::HalfWayMapGenerator
        typedef bp::class_< osgUtil::HalfWayMapGenerator, bp::bases< osgUtil::CubeMapGenerator >, osg::ref_ptr< ::osgUtil::HalfWayMapGenerator >, boost::noncopyable > HalfWayMapGenerator_exposer_t;
        HalfWayMapGenerator_exposer_t HalfWayMapGenerator_exposer = HalfWayMapGenerator_exposer_t( "HalfWayMapGenerator", bp::no_init );
        bp::scope HalfWayMapGenerator_scope( HalfWayMapGenerator_exposer );
        HalfWayMapGenerator_exposer.def( bp::init< osg::Vec3 const &, bp::optional< int > >(( bp::arg("light_direction"), bp::arg("texture_size")=(int)(64) )) );
        bp::implicitly_convertible< osg::Vec3 const &, osgUtil::HalfWayMapGenerator >();
    }

}
