// This file has been generated by Py++.

#include "boost/python.hpp"
#include "indexing_suite/container_suite.hpp"
#include "indexing_suite/set.hpp"
#include "wrap_osgUtil.h"
#include "_PolytopeIntersection__value_traits.pypp.hpp"
#include "PolytopeIntersections.pypp.hpp"

namespace bp = boost::python;

void register_PolytopeIntersections_class(){

    { //::std::set< osgUtil::PolytopeIntersector::Intersection >
        typedef bp::class_< std::set< osgUtil::PolytopeIntersector::Intersection > > PolytopeIntersections_exposer_t;
        PolytopeIntersections_exposer_t PolytopeIntersections_exposer = PolytopeIntersections_exposer_t( "PolytopeIntersections" );
        bp::scope PolytopeIntersections_scope( PolytopeIntersections_exposer );
        PolytopeIntersections_exposer.def( bp::indexing::set_suite< std::set< osgUtil::PolytopeIntersector::Intersection > >() );
    }

}
