// This file has been generated by Py++.

#include "boost/python.hpp"
#include "indexing_suite/container_suite.hpp"
#include "indexing_suite/set.hpp"
#include "wrap_osgUtil.h"
#include "ProgramSet.pypp.hpp"

namespace bp = boost::python;

void register_ProgramSet_class(){

    { //::std::set< osg::Program* >
        typedef bp::class_< std::set< osg::Program* > > ProgramSet_exposer_t;
        ProgramSet_exposer_t ProgramSet_exposer = ProgramSet_exposer_t( "ProgramSet" );
        bp::scope ProgramSet_scope( ProgramSet_exposer );
        ProgramSet_exposer.def( bp::indexing::set_suite< std::set< osg::Program* > >::with_policies(bp::return_internal_reference< >()) );
    }

}
