// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osgUtil.h"
#include "wrap_referenced.h"
#include "ReflectionMapGenerator.pypp.hpp"

namespace bp = boost::python;

void register_ReflectionMapGenerator_class(){

    { //::osgUtil::ReflectionMapGenerator
        typedef bp::class_< osgUtil::ReflectionMapGenerator, bp::bases< osgUtil::CubeMapGenerator >, osg::ref_ptr< ::osgUtil::ReflectionMapGenerator >, boost::noncopyable > ReflectionMapGenerator_exposer_t;
        ReflectionMapGenerator_exposer_t ReflectionMapGenerator_exposer = ReflectionMapGenerator_exposer_t( "ReflectionMapGenerator", bp::no_init );
        bp::scope ReflectionMapGenerator_scope( ReflectionMapGenerator_exposer );
        ReflectionMapGenerator_exposer.def( bp::init< bp::optional< int > >(( bp::arg("texture_size")=(int)(64) )) );
        bp::implicitly_convertible< int, osgUtil::ReflectionMapGenerator >();
    }

}
