// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osg.h"
#include "wrap_referenced.h"
#include "Capsule.pypp.hpp"

namespace bp = boost::python;

struct Capsule_wrapper : osg::Capsule, bp::wrapper< osg::Capsule > {

    Capsule_wrapper( )
    : osg::Capsule( )
      , bp::wrapper< osg::Capsule >(){
        // null constructor
    
    }

    Capsule_wrapper(::osg::Vec3 const & center, float radius, float height )
    : osg::Capsule( boost::ref(center), radius, height )
      , bp::wrapper< osg::Capsule >(){
        // constructor
    
    }

    virtual void accept( ::osg::ShapeVisitor & sv ) {
        if( bp::override func_accept = this->get_override( "accept" ) )
            func_accept( boost::ref(sv) );
        else{
            this->osg::Capsule::accept( boost::ref(sv) );
        }
    }
    
    void default_accept( ::osg::ShapeVisitor & sv ) {
        osg::Capsule::accept( boost::ref(sv) );
    }

    virtual void accept( ::osg::ConstShapeVisitor & csv ) const  {
        if( bp::override func_accept = this->get_override( "accept" ) )
            func_accept( boost::ref(csv) );
        else{
            this->osg::Capsule::accept( boost::ref(csv) );
        }
    }
    
    void default_accept( ::osg::ConstShapeVisitor & csv ) const  {
        osg::Capsule::accept( boost::ref(csv) );
    }

    virtual char const * className(  ) const  {
        if( bp::override func_className = this->get_override( "className" ) )
            return func_className(  );
        else{
            return this->osg::Capsule::className(  );
        }
    }
    
    char const * default_className(  ) const  {
        return osg::Capsule::className( );
    }

    virtual ::osg::Object * clone( ::osg::CopyOp const & copyop ) const  {
        if( bp::override func_clone = this->get_override( "clone" ) )
            return func_clone( boost::ref(copyop) );
        else{
            return this->osg::Capsule::clone( boost::ref(copyop) );
        }
    }
    
    ::osg::Object * default_clone( ::osg::CopyOp const & copyop ) const  {
        return osg::Capsule::clone( boost::ref(copyop) );
    }

    virtual ::osg::Object * cloneType(  ) const  {
        if( bp::override func_cloneType = this->get_override( "cloneType" ) )
            return func_cloneType(  );
        else{
            return this->osg::Capsule::cloneType(  );
        }
    }
    
    ::osg::Object * default_cloneType(  ) const  {
        return osg::Capsule::cloneType( );
    }

    virtual bool isSameKindAs( ::osg::Object const * obj ) const  {
        if( bp::override func_isSameKindAs = this->get_override( "isSameKindAs" ) )
            return func_isSameKindAs( boost::python::ptr(obj) );
        else{
            return this->osg::Capsule::isSameKindAs( boost::python::ptr(obj) );
        }
    }
    
    bool default_isSameKindAs( ::osg::Object const * obj ) const  {
        return osg::Capsule::isSameKindAs( boost::python::ptr(obj) );
    }

    virtual char const * libraryName(  ) const  {
        if( bp::override func_libraryName = this->get_override( "libraryName" ) )
            return func_libraryName(  );
        else{
            return this->osg::Capsule::libraryName(  );
        }
    }
    
    char const * default_libraryName(  ) const  {
        return osg::Capsule::libraryName( );
    }

};

void register_Capsule_class(){

    bp::class_< Capsule_wrapper, bp::bases< osg::Shape >, osg::ref_ptr< ::osg::Capsule >, boost::noncopyable >( "Capsule", bp::no_init )    
        .def( bp::init< >() )    
        .def( bp::init< osg::Vec3 const &, float, float >(( bp::arg("center"), bp::arg("radius"), bp::arg("height") )) )    
        .def( 
            "accept"
            , (void ( ::osg::Capsule::* )( ::osg::ShapeVisitor & ) )(&::osg::Capsule::accept)
            , (void ( Capsule_wrapper::* )( ::osg::ShapeVisitor & ) )(&Capsule_wrapper::default_accept)
            , ( bp::arg("sv") ) )    
        .def( 
            "accept"
            , (void ( ::osg::Capsule::* )( ::osg::ConstShapeVisitor & ) const)(&::osg::Capsule::accept)
            , (void ( Capsule_wrapper::* )( ::osg::ConstShapeVisitor & ) const)(&Capsule_wrapper::default_accept)
            , ( bp::arg("csv") ) )    
        .def( 
            "className"
            , (char const * ( ::osg::Capsule::* )(  ) const)(&::osg::Capsule::className)
            , (char const * ( Capsule_wrapper::* )(  ) const)(&Capsule_wrapper::default_className) )    
        .def( 
            "clone"
            , (::osg::Object * ( ::osg::Capsule::* )( ::osg::CopyOp const & ) const)(&::osg::Capsule::clone)
            , (::osg::Object * ( Capsule_wrapper::* )( ::osg::CopyOp const & ) const)(&Capsule_wrapper::default_clone)
            , ( bp::arg("copyop") )
            , bp::return_value_policy< bp::reference_existing_object >() )    
        .def( 
            "cloneType"
            , (::osg::Object * ( ::osg::Capsule::* )(  ) const)(&::osg::Capsule::cloneType)
            , (::osg::Object * ( Capsule_wrapper::* )(  ) const)(&Capsule_wrapper::default_cloneType)
            , bp::return_value_policy< bp::reference_existing_object >() )    
        .def( 
            "computeRotationMatrix"
            , (::osg::Matrix ( ::osg::Capsule::* )(  ) const)( &::osg::Capsule::computeRotationMatrix ) )    
        .def( 
            "getCenter"
            , (::osg::Vec3 const & ( ::osg::Capsule::* )(  ) const)( &::osg::Capsule::getCenter )
            , bp::return_internal_reference< >() )    
        .def( 
            "getHeight"
            , (float ( ::osg::Capsule::* )(  ) const)( &::osg::Capsule::getHeight ) )    
        .def( 
            "getRadius"
            , (float ( ::osg::Capsule::* )(  ) const)( &::osg::Capsule::getRadius ) )    
        .def( 
            "getRotation"
            , (::osg::Quat const & ( ::osg::Capsule::* )(  ) const)( &::osg::Capsule::getRotation )
            , bp::return_internal_reference< >() )    
        .def( 
            "isSameKindAs"
            , (bool ( ::osg::Capsule::* )( ::osg::Object const * ) const)(&::osg::Capsule::isSameKindAs)
            , (bool ( Capsule_wrapper::* )( ::osg::Object const * ) const)(&Capsule_wrapper::default_isSameKindAs)
            , ( bp::arg("obj") ) )    
        .def( 
            "libraryName"
            , (char const * ( ::osg::Capsule::* )(  ) const)(&::osg::Capsule::libraryName)
            , (char const * ( Capsule_wrapper::* )(  ) const)(&Capsule_wrapper::default_libraryName) )    
        .def( 
            "set"
            , (void ( ::osg::Capsule::* )( ::osg::Vec3 const &,float,float ) )( &::osg::Capsule::set )
            , ( bp::arg("center"), bp::arg("radius"), bp::arg("height") ) )    
        .def( 
            "setCenter"
            , (void ( ::osg::Capsule::* )( ::osg::Vec3 const & ) )( &::osg::Capsule::setCenter )
            , ( bp::arg("center") ) )    
        .def( 
            "setHeight"
            , (void ( ::osg::Capsule::* )( float ) )( &::osg::Capsule::setHeight )
            , ( bp::arg("height") ) )    
        .def( 
            "setRadius"
            , (void ( ::osg::Capsule::* )( float ) )( &::osg::Capsule::setRadius )
            , ( bp::arg("radius") ) )    
        .def( 
            "setRotation"
            , (void ( ::osg::Capsule::* )( ::osg::Quat const & ) )( &::osg::Capsule::setRotation )
            , ( bp::arg("quat") ) )    
        .def( 
            "valid"
            , (bool ( ::osg::Capsule::* )(  ) const)( &::osg::Capsule::valid ) )    
        .def( 
            "zeroRotation"
            , (bool ( ::osg::Capsule::* )(  ) const)( &::osg::Capsule::zeroRotation ) );

}
