// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osg.h"
#include "wrap_referenced.h"
#include "Fog.pypp.hpp"

namespace bp = boost::python;

struct Fog_wrapper : osg::Fog, bp::wrapper< osg::Fog > {

    Fog_wrapper( )
    : osg::Fog( )
      , bp::wrapper< osg::Fog >(){
        // null constructor
    
    }

    virtual void apply( ::osg::State & state ) const  {
        if( bp::override func_apply = this->get_override( "apply" ) )
            func_apply( boost::ref(state) );
        else{
            this->osg::Fog::apply( boost::ref(state) );
        }
    }
    
    void default_apply( ::osg::State & state ) const  {
        osg::Fog::apply( boost::ref(state) );
    }

    virtual char const * className(  ) const  {
        if( bp::override func_className = this->get_override( "className" ) )
            return func_className(  );
        else{
            return this->osg::Fog::className(  );
        }
    }
    
    char const * default_className(  ) const  {
        return osg::Fog::className( );
    }

    virtual ::osg::Object * clone( ::osg::CopyOp const & copyop ) const  {
        if( bp::override func_clone = this->get_override( "clone" ) )
            return func_clone( boost::ref(copyop) );
        else{
            return this->osg::Fog::clone( boost::ref(copyop) );
        }
    }
    
    ::osg::Object * default_clone( ::osg::CopyOp const & copyop ) const  {
        return osg::Fog::clone( boost::ref(copyop) );
    }

    virtual ::osg::Object * cloneType(  ) const  {
        if( bp::override func_cloneType = this->get_override( "cloneType" ) )
            return func_cloneType(  );
        else{
            return this->osg::Fog::cloneType(  );
        }
    }
    
    ::osg::Object * default_cloneType(  ) const  {
        return osg::Fog::cloneType( );
    }

    virtual bool getModeUsage( ::osg::StateAttribute::ModeUsage & usage ) const  {
        if( bp::override func_getModeUsage = this->get_override( "getModeUsage" ) )
            return func_getModeUsage( boost::ref(usage) );
        else{
            return this->osg::Fog::getModeUsage( boost::ref(usage) );
        }
    }
    
    bool default_getModeUsage( ::osg::StateAttribute::ModeUsage & usage ) const  {
        return osg::Fog::getModeUsage( boost::ref(usage) );
    }

    virtual ::osg::StateAttribute::Type getType(  ) const  {
        if( bp::override func_getType = this->get_override( "getType" ) )
            return func_getType(  );
        else{
            return this->osg::Fog::getType(  );
        }
    }
    
    ::osg::StateAttribute::Type default_getType(  ) const  {
        return osg::Fog::getType( );
    }

    virtual bool isSameKindAs( ::osg::Object const * obj ) const  {
        if( bp::override func_isSameKindAs = this->get_override( "isSameKindAs" ) )
            return func_isSameKindAs( boost::python::ptr(obj) );
        else{
            return this->osg::Fog::isSameKindAs( boost::python::ptr(obj) );
        }
    }
    
    bool default_isSameKindAs( ::osg::Object const * obj ) const  {
        return osg::Fog::isSameKindAs( boost::python::ptr(obj) );
    }

    virtual char const * libraryName(  ) const  {
        if( bp::override func_libraryName = this->get_override( "libraryName" ) )
            return func_libraryName(  );
        else{
            return this->osg::Fog::libraryName(  );
        }
    }
    
    char const * default_libraryName(  ) const  {
        return osg::Fog::libraryName( );
    }

    virtual ::osg::Texture * asTexture(  ) {
        if( bp::override func_asTexture = this->get_override( "asTexture" ) )
            return func_asTexture(  );
        else{
            return this->osg::StateAttribute::asTexture(  );
        }
    }
    
    ::osg::Texture * default_asTexture(  ) {
        return osg::StateAttribute::asTexture( );
    }

    virtual ::osg::Texture const * asTexture(  ) const  {
        if( bp::override func_asTexture = this->get_override( "asTexture" ) )
            return func_asTexture(  );
        else{
            return this->osg::StateAttribute::asTexture(  );
        }
    }
    
    ::osg::Texture const * default_asTexture(  ) const  {
        return osg::StateAttribute::asTexture( );
    }

    virtual bool checkValidityOfAssociatedModes( ::osg::State & arg0 ) const  {
        if( bp::override func_checkValidityOfAssociatedModes = this->get_override( "checkValidityOfAssociatedModes" ) )
            return func_checkValidityOfAssociatedModes( boost::ref(arg0) );
        else{
            return this->osg::StateAttribute::checkValidityOfAssociatedModes( boost::ref(arg0) );
        }
    }
    
    bool default_checkValidityOfAssociatedModes( ::osg::State & arg0 ) const  {
        return osg::StateAttribute::checkValidityOfAssociatedModes( boost::ref(arg0) );
    }

    virtual void compileGLObjects( ::osg::State & arg0 ) const  {
        if( bp::override func_compileGLObjects = this->get_override( "compileGLObjects" ) )
            func_compileGLObjects( boost::ref(arg0) );
        else{
            this->osg::StateAttribute::compileGLObjects( boost::ref(arg0) );
        }
    }
    
    void default_compileGLObjects( ::osg::State & arg0 ) const  {
        osg::StateAttribute::compileGLObjects( boost::ref(arg0) );
    }

    virtual unsigned int getMember(  ) const  {
        if( bp::override func_getMember = this->get_override( "getMember" ) )
            return func_getMember(  );
        else{
            return this->osg::StateAttribute::getMember(  );
        }
    }
    
    unsigned int default_getMember(  ) const  {
        return osg::StateAttribute::getMember( );
    }

    virtual bool isTextureAttribute(  ) const  {
        if( bp::override func_isTextureAttribute = this->get_override( "isTextureAttribute" ) )
            return func_isTextureAttribute(  );
        else{
            return this->osg::StateAttribute::isTextureAttribute(  );
        }
    }
    
    bool default_isTextureAttribute(  ) const  {
        return osg::StateAttribute::isTextureAttribute( );
    }

    virtual void resizeGLObjectBuffers( unsigned int arg0 ) {
        if( bp::override func_resizeGLObjectBuffers = this->get_override( "resizeGLObjectBuffers" ) )
            func_resizeGLObjectBuffers( arg0 );
        else{
            this->osg::StateAttribute::resizeGLObjectBuffers( arg0 );
        }
    }
    
    void default_resizeGLObjectBuffers( unsigned int arg0 ) {
        osg::StateAttribute::resizeGLObjectBuffers( arg0 );
    }

};

void register_Fog_class(){

    { //::osg::Fog
        typedef bp::class_< Fog_wrapper, bp::bases< osg::StateAttribute >, osg::ref_ptr< ::osg::Fog >, boost::noncopyable > Fog_exposer_t;
        Fog_exposer_t Fog_exposer = Fog_exposer_t( "Fog", "\n Fog - encapsulates OpenGL fog state.\n", bp::no_init );
        bp::scope Fog_scope( Fog_exposer );
        bp::enum_< osg::Fog::FogCoordinateSource>("FogCoordinateSource")
            .value("FOG_COORDINATE", osg::Fog::FOG_COORDINATE)
            .value("FRAGMENT_DEPTH", osg::Fog::FRAGMENT_DEPTH)
            .export_values()
            ;
        bp::enum_< osg::Fog::Mode>("Mode")
            .value("LINEAR", osg::Fog::LINEAR)
            .value("EXP", osg::Fog::EXP)
            .value("EXP2", osg::Fog::EXP2)
            .export_values()
            ;
        Fog_exposer.def( bp::init< >("\n Fog - encapsulates OpenGL fog state.\n") );
        { //::osg::Fog::apply
        
            typedef void ( ::osg::Fog::*apply_function_type )( ::osg::State & ) const;
            typedef void ( Fog_wrapper::*default_apply_function_type )( ::osg::State & ) const;
            
            Fog_exposer.def( 
                "apply"
                , apply_function_type(&::osg::Fog::apply)
                , default_apply_function_type(&Fog_wrapper::default_apply)
                , ( bp::arg("state") ) );
        
        }
        { //::osg::Fog::className
        
            typedef char const * ( ::osg::Fog::*className_function_type )(  ) const;
            typedef char const * ( Fog_wrapper::*default_className_function_type )(  ) const;
            
            Fog_exposer.def( 
                "className"
                , className_function_type(&::osg::Fog::className)
                , default_className_function_type(&Fog_wrapper::default_className) );
        
        }
        { //::osg::Fog::clone
        
            typedef ::osg::Object * ( ::osg::Fog::*clone_function_type )( ::osg::CopyOp const & ) const;
            typedef ::osg::Object * ( Fog_wrapper::*default_clone_function_type )( ::osg::CopyOp const & ) const;
            
            Fog_exposer.def( 
                "clone"
                , clone_function_type(&::osg::Fog::clone)
                , default_clone_function_type(&Fog_wrapper::default_clone)
                , ( bp::arg("copyop") )
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::osg::Fog::cloneType
        
            typedef ::osg::Object * ( ::osg::Fog::*cloneType_function_type )(  ) const;
            typedef ::osg::Object * ( Fog_wrapper::*default_cloneType_function_type )(  ) const;
            
            Fog_exposer.def( 
                "cloneType"
                , cloneType_function_type(&::osg::Fog::cloneType)
                , default_cloneType_function_type(&Fog_wrapper::default_cloneType)
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::osg::Fog::getColor
        
            typedef ::osg::Vec4 const & ( ::osg::Fog::*getColor_function_type )(  ) const;
            
            Fog_exposer.def( 
                "getColor"
                , getColor_function_type( &::osg::Fog::getColor )
                , bp::return_internal_reference< >() );
        
        }
        { //::osg::Fog::getDensity
        
            typedef float ( ::osg::Fog::*getDensity_function_type )(  ) const;
            
            Fog_exposer.def( 
                "getDensity"
                , getDensity_function_type( &::osg::Fog::getDensity ) );
        
        }
        { //::osg::Fog::getEnd
        
            typedef float ( ::osg::Fog::*getEnd_function_type )(  ) const;
            
            Fog_exposer.def( 
                "getEnd"
                , getEnd_function_type( &::osg::Fog::getEnd ) );
        
        }
        { //::osg::Fog::getFogCoordinateSource
        
            typedef ::GLint ( ::osg::Fog::*getFogCoordinateSource_function_type )(  ) const;
            
            Fog_exposer.def( 
                "getFogCoordinateSource"
                , getFogCoordinateSource_function_type( &::osg::Fog::getFogCoordinateSource ) );
        
        }
        { //::osg::Fog::getMode
        
            typedef ::osg::Fog::Mode ( ::osg::Fog::*getMode_function_type )(  ) const;
            
            Fog_exposer.def( 
                "getMode"
                , getMode_function_type( &::osg::Fog::getMode ) );
        
        }
        { //::osg::Fog::getModeUsage
        
            typedef bool ( ::osg::Fog::*getModeUsage_function_type )( ::osg::StateAttribute::ModeUsage & ) const;
            typedef bool ( Fog_wrapper::*default_getModeUsage_function_type )( ::osg::StateAttribute::ModeUsage & ) const;
            
            Fog_exposer.def( 
                "getModeUsage"
                , getModeUsage_function_type(&::osg::Fog::getModeUsage)
                , default_getModeUsage_function_type(&Fog_wrapper::default_getModeUsage)
                , ( bp::arg("usage") ) );
        
        }
        { //::osg::Fog::getStart
        
            typedef float ( ::osg::Fog::*getStart_function_type )(  ) const;
            
            Fog_exposer.def( 
                "getStart"
                , getStart_function_type( &::osg::Fog::getStart ) );
        
        }
        { //::osg::Fog::getType
        
            typedef ::osg::StateAttribute::Type ( ::osg::Fog::*getType_function_type )(  ) const;
            typedef ::osg::StateAttribute::Type ( Fog_wrapper::*default_getType_function_type )(  ) const;
            
            Fog_exposer.def( 
                "getType"
                , getType_function_type(&::osg::Fog::getType)
                , default_getType_function_type(&Fog_wrapper::default_getType) );
        
        }
        { //::osg::Fog::getUseRadialFog
        
            typedef bool ( ::osg::Fog::*getUseRadialFog_function_type )(  ) const;
            
            Fog_exposer.def( 
                "getUseRadialFog"
                , getUseRadialFog_function_type( &::osg::Fog::getUseRadialFog ) );
        
        }
        { //::osg::Fog::isSameKindAs
        
            typedef bool ( ::osg::Fog::*isSameKindAs_function_type )( ::osg::Object const * ) const;
            typedef bool ( Fog_wrapper::*default_isSameKindAs_function_type )( ::osg::Object const * ) const;
            
            Fog_exposer.def( 
                "isSameKindAs"
                , isSameKindAs_function_type(&::osg::Fog::isSameKindAs)
                , default_isSameKindAs_function_type(&Fog_wrapper::default_isSameKindAs)
                , ( bp::arg("obj") ) );
        
        }
        { //::osg::Fog::libraryName
        
            typedef char const * ( ::osg::Fog::*libraryName_function_type )(  ) const;
            typedef char const * ( Fog_wrapper::*default_libraryName_function_type )(  ) const;
            
            Fog_exposer.def( 
                "libraryName"
                , libraryName_function_type(&::osg::Fog::libraryName)
                , default_libraryName_function_type(&Fog_wrapper::default_libraryName) );
        
        }
        { //::osg::Fog::setColor
        
            typedef void ( ::osg::Fog::*setColor_function_type )( ::osg::Vec4 const & ) ;
            
            Fog_exposer.def( 
                "setColor"
                , setColor_function_type( &::osg::Fog::setColor )
                , ( bp::arg("color") ) );
        
        }
        { //::osg::Fog::setDensity
        
            typedef void ( ::osg::Fog::*setDensity_function_type )( float ) ;
            
            Fog_exposer.def( 
                "setDensity"
                , setDensity_function_type( &::osg::Fog::setDensity )
                , ( bp::arg("density") ) );
        
        }
        { //::osg::Fog::setEnd
        
            typedef void ( ::osg::Fog::*setEnd_function_type )( float ) ;
            
            Fog_exposer.def( 
                "setEnd"
                , setEnd_function_type( &::osg::Fog::setEnd )
                , ( bp::arg("end") ) );
        
        }
        { //::osg::Fog::setFogCoordinateSource
        
            typedef void ( ::osg::Fog::*setFogCoordinateSource_function_type )( ::GLint ) ;
            
            Fog_exposer.def( 
                "setFogCoordinateSource"
                , setFogCoordinateSource_function_type( &::osg::Fog::setFogCoordinateSource )
                , ( bp::arg("source") ) );
        
        }
        { //::osg::Fog::setMode
        
            typedef void ( ::osg::Fog::*setMode_function_type )( ::osg::Fog::Mode ) ;
            
            Fog_exposer.def( 
                "setMode"
                , setMode_function_type( &::osg::Fog::setMode )
                , ( bp::arg("mode") ) );
        
        }
        { //::osg::Fog::setStart
        
            typedef void ( ::osg::Fog::*setStart_function_type )( float ) ;
            
            Fog_exposer.def( 
                "setStart"
                , setStart_function_type( &::osg::Fog::setStart )
                , ( bp::arg("start") ) );
        
        }
        { //::osg::Fog::setUseRadialFog
        
            typedef void ( ::osg::Fog::*setUseRadialFog_function_type )( bool ) ;
            
            Fog_exposer.def( 
                "setUseRadialFog"
                , setUseRadialFog_function_type( &::osg::Fog::setUseRadialFog )
                , ( bp::arg("useRadialFog") ) );
        
        }
        { //::osg::StateAttribute::asTexture
        
            typedef ::osg::Texture * ( ::osg::StateAttribute::*asTexture_function_type )(  ) ;
            typedef ::osg::Texture * ( Fog_wrapper::*default_asTexture_function_type )(  ) ;
            
            Fog_exposer.def( 
                "asTexture"
                , asTexture_function_type(&::osg::StateAttribute::asTexture)
                , default_asTexture_function_type(&Fog_wrapper::default_asTexture)
                , bp::return_internal_reference< >() );
        
        }
        { //::osg::StateAttribute::asTexture
        
            typedef ::osg::Texture const * ( ::osg::StateAttribute::*asTexture_function_type )(  ) const;
            typedef ::osg::Texture const * ( Fog_wrapper::*default_asTexture_function_type )(  ) const;
            
            Fog_exposer.def( 
                "asTexture"
                , asTexture_function_type(&::osg::StateAttribute::asTexture)
                , default_asTexture_function_type(&Fog_wrapper::default_asTexture)
                , bp::return_internal_reference< >() );
        
        }
        { //::osg::StateAttribute::checkValidityOfAssociatedModes
        
            typedef bool ( ::osg::StateAttribute::*checkValidityOfAssociatedModes_function_type )( ::osg::State & ) const;
            typedef bool ( Fog_wrapper::*default_checkValidityOfAssociatedModes_function_type )( ::osg::State & ) const;
            
            Fog_exposer.def( 
                "checkValidityOfAssociatedModes"
                , checkValidityOfAssociatedModes_function_type(&::osg::StateAttribute::checkValidityOfAssociatedModes)
                , default_checkValidityOfAssociatedModes_function_type(&Fog_wrapper::default_checkValidityOfAssociatedModes)
                , ( bp::arg("arg0") ) );
        
        }
        { //::osg::StateAttribute::compileGLObjects
        
            typedef void ( ::osg::StateAttribute::*compileGLObjects_function_type )( ::osg::State & ) const;
            typedef void ( Fog_wrapper::*default_compileGLObjects_function_type )( ::osg::State & ) const;
            
            Fog_exposer.def( 
                "compileGLObjects"
                , compileGLObjects_function_type(&::osg::StateAttribute::compileGLObjects)
                , default_compileGLObjects_function_type(&Fog_wrapper::default_compileGLObjects)
                , ( bp::arg("arg0") ) );
        
        }
        { //::osg::StateAttribute::getMember
        
            typedef unsigned int ( ::osg::StateAttribute::*getMember_function_type )(  ) const;
            typedef unsigned int ( Fog_wrapper::*default_getMember_function_type )(  ) const;
            
            Fog_exposer.def( 
                "getMember"
                , getMember_function_type(&::osg::StateAttribute::getMember)
                , default_getMember_function_type(&Fog_wrapper::default_getMember) );
        
        }
        { //::osg::StateAttribute::isTextureAttribute
        
            typedef bool ( ::osg::StateAttribute::*isTextureAttribute_function_type )(  ) const;
            typedef bool ( Fog_wrapper::*default_isTextureAttribute_function_type )(  ) const;
            
            Fog_exposer.def( 
                "isTextureAttribute"
                , isTextureAttribute_function_type(&::osg::StateAttribute::isTextureAttribute)
                , default_isTextureAttribute_function_type(&Fog_wrapper::default_isTextureAttribute) );
        
        }
        { //::osg::StateAttribute::resizeGLObjectBuffers
        
            typedef void ( ::osg::StateAttribute::*resizeGLObjectBuffers_function_type )( unsigned int ) ;
            typedef void ( Fog_wrapper::*default_resizeGLObjectBuffers_function_type )( unsigned int ) ;
            
            Fog_exposer.def( 
                "resizeGLObjectBuffers"
                , resizeGLObjectBuffers_function_type(&::osg::StateAttribute::resizeGLObjectBuffers)
                , default_resizeGLObjectBuffers_function_type(&Fog_wrapper::default_resizeGLObjectBuffers)
                , ( bp::arg("arg0") ) );
        
        }
    }

}
