// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osg.h"
#include "wrap_referenced.h"
#include "GraphicsCostEstimator.pypp.hpp"

namespace bp = boost::python;

void register_GraphicsCostEstimator_class(){

    bp::class_< osg::GraphicsCostEstimator, bp::bases< osg::Referenced >, osg::ref_ptr< ::osg::GraphicsCostEstimator >, boost::noncopyable >( "GraphicsCostEstimator", bp::no_init )    
        .def( bp::init< >() )    
        .def( 
            "calibrate"
            , (void ( ::osg::GraphicsCostEstimator::* )( ::osg::RenderInfo & ) )( &::osg::GraphicsCostEstimator::calibrate )
            , ( bp::arg("renderInfo") )
            , "\n calibrate the costs of various compile and draw operations\n" )    
        .def( 
            "estimateCompileCost"
            , (::osg::CostPair ( ::osg::GraphicsCostEstimator::* )( ::osg::Geometry const * ) const)( &::osg::GraphicsCostEstimator::estimateCompileCost )
            , ( bp::arg("geometry") ) )    
        .def( 
            "estimateCompileCost"
            , (::osg::CostPair ( ::osg::GraphicsCostEstimator::* )( ::osg::Texture const * ) const)( &::osg::GraphicsCostEstimator::estimateCompileCost )
            , ( bp::arg("texture") ) )    
        .def( 
            "estimateCompileCost"
            , (::osg::CostPair ( ::osg::GraphicsCostEstimator::* )( ::osg::Program const * ) const)( &::osg::GraphicsCostEstimator::estimateCompileCost )
            , ( bp::arg("program") ) )    
        .def( 
            "estimateCompileCost"
            , (::osg::CostPair ( ::osg::GraphicsCostEstimator::* )( ::osg::Node const * ) const)( &::osg::GraphicsCostEstimator::estimateCompileCost )
            , ( bp::arg("node") ) )    
        .def( 
            "estimateDrawCost"
            , (::osg::CostPair ( ::osg::GraphicsCostEstimator::* )( ::osg::Geometry const * ) const)( &::osg::GraphicsCostEstimator::estimateDrawCost )
            , ( bp::arg("geometry") ) )    
        .def( 
            "estimateDrawCost"
            , (::osg::CostPair ( ::osg::GraphicsCostEstimator::* )( ::osg::Texture const * ) const)( &::osg::GraphicsCostEstimator::estimateDrawCost )
            , ( bp::arg("texture") ) )    
        .def( 
            "estimateDrawCost"
            , (::osg::CostPair ( ::osg::GraphicsCostEstimator::* )( ::osg::Program const * ) const)( &::osg::GraphicsCostEstimator::estimateDrawCost )
            , ( bp::arg("program") ) )    
        .def( 
            "estimateDrawCost"
            , (::osg::CostPair ( ::osg::GraphicsCostEstimator::* )( ::osg::Node const * ) const)( &::osg::GraphicsCostEstimator::estimateDrawCost )
            , ( bp::arg("node") ) )    
        .def( 
            "setDefaults"
            , (void ( ::osg::GraphicsCostEstimator::* )(  ) )( &::osg::GraphicsCostEstimator::setDefaults )
            , "\n set defaults for computing the costs.\n" );

}
