// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osg.h"
#include "wrap_referenced.h"
#include "PatchParameter.pypp.hpp"

namespace bp = boost::python;

struct PatchParameter_wrapper : osg::PatchParameter, bp::wrapper< osg::PatchParameter > {

    PatchParameter_wrapper(::GLint vertices=3 )
    : osg::PatchParameter( vertices )
      , bp::wrapper< osg::PatchParameter >(){
        // constructor
    
    }

    virtual void apply( ::osg::State & state ) const  {
        if( bp::override func_apply = this->get_override( "apply" ) )
            func_apply( boost::ref(state) );
        else{
            this->osg::PatchParameter::apply( boost::ref(state) );
        }
    }
    
    void default_apply( ::osg::State & state ) const  {
        osg::PatchParameter::apply( boost::ref(state) );
    }

    virtual char const * className(  ) const  {
        if( bp::override func_className = this->get_override( "className" ) )
            return func_className(  );
        else{
            return this->osg::PatchParameter::className(  );
        }
    }
    
    char const * default_className(  ) const  {
        return osg::PatchParameter::className( );
    }

    virtual ::osg::Object * clone( ::osg::CopyOp const & copyop ) const  {
        if( bp::override func_clone = this->get_override( "clone" ) )
            return func_clone( boost::ref(copyop) );
        else{
            return this->osg::PatchParameter::clone( boost::ref(copyop) );
        }
    }
    
    ::osg::Object * default_clone( ::osg::CopyOp const & copyop ) const  {
        return osg::PatchParameter::clone( boost::ref(copyop) );
    }

    virtual ::osg::Object * cloneType(  ) const  {
        if( bp::override func_cloneType = this->get_override( "cloneType" ) )
            return func_cloneType(  );
        else{
            return this->osg::PatchParameter::cloneType(  );
        }
    }
    
    ::osg::Object * default_cloneType(  ) const  {
        return osg::PatchParameter::cloneType( );
    }

    virtual ::osg::StateAttribute::Type getType(  ) const  {
        if( bp::override func_getType = this->get_override( "getType" ) )
            return func_getType(  );
        else{
            return this->osg::PatchParameter::getType(  );
        }
    }
    
    ::osg::StateAttribute::Type default_getType(  ) const  {
        return osg::PatchParameter::getType( );
    }

    virtual bool isSameKindAs( ::osg::Object const * obj ) const  {
        if( bp::override func_isSameKindAs = this->get_override( "isSameKindAs" ) )
            return func_isSameKindAs( boost::python::ptr(obj) );
        else{
            return this->osg::PatchParameter::isSameKindAs( boost::python::ptr(obj) );
        }
    }
    
    bool default_isSameKindAs( ::osg::Object const * obj ) const  {
        return osg::PatchParameter::isSameKindAs( boost::python::ptr(obj) );
    }

    virtual char const * libraryName(  ) const  {
        if( bp::override func_libraryName = this->get_override( "libraryName" ) )
            return func_libraryName(  );
        else{
            return this->osg::PatchParameter::libraryName(  );
        }
    }
    
    char const * default_libraryName(  ) const  {
        return osg::PatchParameter::libraryName( );
    }

    virtual ::osg::Texture * asTexture(  ) {
        if( bp::override func_asTexture = this->get_override( "asTexture" ) )
            return func_asTexture(  );
        else{
            return this->osg::StateAttribute::asTexture(  );
        }
    }
    
    ::osg::Texture * default_asTexture(  ) {
        return osg::StateAttribute::asTexture( );
    }

    virtual ::osg::Texture const * asTexture(  ) const  {
        if( bp::override func_asTexture = this->get_override( "asTexture" ) )
            return func_asTexture(  );
        else{
            return this->osg::StateAttribute::asTexture(  );
        }
    }
    
    ::osg::Texture const * default_asTexture(  ) const  {
        return osg::StateAttribute::asTexture( );
    }

    virtual bool checkValidityOfAssociatedModes( ::osg::State & arg0 ) const  {
        if( bp::override func_checkValidityOfAssociatedModes = this->get_override( "checkValidityOfAssociatedModes" ) )
            return func_checkValidityOfAssociatedModes( boost::ref(arg0) );
        else{
            return this->osg::StateAttribute::checkValidityOfAssociatedModes( boost::ref(arg0) );
        }
    }
    
    bool default_checkValidityOfAssociatedModes( ::osg::State & arg0 ) const  {
        return osg::StateAttribute::checkValidityOfAssociatedModes( boost::ref(arg0) );
    }

    virtual void compileGLObjects( ::osg::State & arg0 ) const  {
        if( bp::override func_compileGLObjects = this->get_override( "compileGLObjects" ) )
            func_compileGLObjects( boost::ref(arg0) );
        else{
            this->osg::StateAttribute::compileGLObjects( boost::ref(arg0) );
        }
    }
    
    void default_compileGLObjects( ::osg::State & arg0 ) const  {
        osg::StateAttribute::compileGLObjects( boost::ref(arg0) );
    }

    virtual unsigned int getMember(  ) const  {
        if( bp::override func_getMember = this->get_override( "getMember" ) )
            return func_getMember(  );
        else{
            return this->osg::StateAttribute::getMember(  );
        }
    }
    
    unsigned int default_getMember(  ) const  {
        return osg::StateAttribute::getMember( );
    }

    virtual bool getModeUsage( ::osg::StateAttribute::ModeUsage & arg0 ) const  {
        if( bp::override func_getModeUsage = this->get_override( "getModeUsage" ) )
            return func_getModeUsage( boost::ref(arg0) );
        else{
            return this->osg::StateAttribute::getModeUsage( boost::ref(arg0) );
        }
    }
    
    bool default_getModeUsage( ::osg::StateAttribute::ModeUsage & arg0 ) const  {
        return osg::StateAttribute::getModeUsage( boost::ref(arg0) );
    }

    virtual bool isTextureAttribute(  ) const  {
        if( bp::override func_isTextureAttribute = this->get_override( "isTextureAttribute" ) )
            return func_isTextureAttribute(  );
        else{
            return this->osg::StateAttribute::isTextureAttribute(  );
        }
    }
    
    bool default_isTextureAttribute(  ) const  {
        return osg::StateAttribute::isTextureAttribute( );
    }

    virtual void resizeGLObjectBuffers( unsigned int arg0 ) {
        if( bp::override func_resizeGLObjectBuffers = this->get_override( "resizeGLObjectBuffers" ) )
            func_resizeGLObjectBuffers( arg0 );
        else{
            this->osg::StateAttribute::resizeGLObjectBuffers( arg0 );
        }
    }
    
    void default_resizeGLObjectBuffers( unsigned int arg0 ) {
        osg::StateAttribute::resizeGLObjectBuffers( arg0 );
    }

};

void register_PatchParameter_class(){

    { //::osg::PatchParameter
        typedef bp::class_< PatchParameter_wrapper, bp::bases< osg::StateAttribute >, osg::ref_ptr< ::osg::PatchParameter >, boost::noncopyable > PatchParameter_exposer_t;
        PatchParameter_exposer_t PatchParameter_exposer = PatchParameter_exposer_t( "PatchParameter", "\n Class which encapsulates glPatchParameter(..).\n", bp::no_init );
        bp::scope PatchParameter_scope( PatchParameter_exposer );
        PatchParameter_exposer.def( bp::init< bp::optional< GLint > >(( bp::arg("vertices")=(::GLint)(3) ), "\n Class which encapsulates glPatchParameter(..).\n") );
        bp::implicitly_convertible< GLint, osg::PatchParameter >();
        { //::osg::PatchParameter::apply
        
            typedef void ( ::osg::PatchParameter::*apply_function_type )( ::osg::State & ) const;
            typedef void ( PatchParameter_wrapper::*default_apply_function_type )( ::osg::State & ) const;
            
            PatchParameter_exposer.def( 
                "apply"
                , apply_function_type(&::osg::PatchParameter::apply)
                , default_apply_function_type(&PatchParameter_wrapper::default_apply)
                , ( bp::arg("state") ) );
        
        }
        { //::osg::PatchParameter::className
        
            typedef char const * ( ::osg::PatchParameter::*className_function_type )(  ) const;
            typedef char const * ( PatchParameter_wrapper::*default_className_function_type )(  ) const;
            
            PatchParameter_exposer.def( 
                "className"
                , className_function_type(&::osg::PatchParameter::className)
                , default_className_function_type(&PatchParameter_wrapper::default_className) );
        
        }
        { //::osg::PatchParameter::clone
        
            typedef ::osg::Object * ( ::osg::PatchParameter::*clone_function_type )( ::osg::CopyOp const & ) const;
            typedef ::osg::Object * ( PatchParameter_wrapper::*default_clone_function_type )( ::osg::CopyOp const & ) const;
            
            PatchParameter_exposer.def( 
                "clone"
                , clone_function_type(&::osg::PatchParameter::clone)
                , default_clone_function_type(&PatchParameter_wrapper::default_clone)
                , ( bp::arg("copyop") )
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::osg::PatchParameter::cloneType
        
            typedef ::osg::Object * ( ::osg::PatchParameter::*cloneType_function_type )(  ) const;
            typedef ::osg::Object * ( PatchParameter_wrapper::*default_cloneType_function_type )(  ) const;
            
            PatchParameter_exposer.def( 
                "cloneType"
                , cloneType_function_type(&::osg::PatchParameter::cloneType)
                , default_cloneType_function_type(&PatchParameter_wrapper::default_cloneType)
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::osg::PatchParameter::getPatchDefaultInnerLevel
        
            typedef ::osg::Vec2 const & ( ::osg::PatchParameter::*getPatchDefaultInnerLevel_function_type )(  ) const;
            
            PatchParameter_exposer.def( 
                "getPatchDefaultInnerLevel"
                , getPatchDefaultInnerLevel_function_type( &::osg::PatchParameter::getPatchDefaultInnerLevel )
                , bp::return_internal_reference< >()
                , " Get GL_PATCH_DEFAULT_INNER_LEVEL parameter." );
        
        }
        { //::osg::PatchParameter::getPatchDefaultOuterLevel
        
            typedef ::osg::Vec4 const & ( ::osg::PatchParameter::*getPatchDefaultOuterLevel_function_type )(  ) const;
            
            PatchParameter_exposer.def( 
                "getPatchDefaultOuterLevel"
                , getPatchDefaultOuterLevel_function_type( &::osg::PatchParameter::getPatchDefaultOuterLevel )
                , bp::return_internal_reference< >()
                , " Get GL_PATCH_DEFAULT_INNER_LEVEL parameter." );
        
        }
        { //::osg::PatchParameter::getType
        
            typedef ::osg::StateAttribute::Type ( ::osg::PatchParameter::*getType_function_type )(  ) const;
            typedef ::osg::StateAttribute::Type ( PatchParameter_wrapper::*default_getType_function_type )(  ) const;
            
            PatchParameter_exposer.def( 
                "getType"
                , getType_function_type(&::osg::PatchParameter::getType)
                , default_getType_function_type(&PatchParameter_wrapper::default_getType) );
        
        }
        { //::osg::PatchParameter::getVertices
        
            typedef ::GLint ( ::osg::PatchParameter::*getVertices_function_type )(  ) const;
            
            PatchParameter_exposer.def( 
                "getVertices"
                , getVertices_function_type( &::osg::PatchParameter::getVertices )
                , " Get GL_PATCH_VERTICES parameter." );
        
        }
        { //::osg::PatchParameter::isSameKindAs
        
            typedef bool ( ::osg::PatchParameter::*isSameKindAs_function_type )( ::osg::Object const * ) const;
            typedef bool ( PatchParameter_wrapper::*default_isSameKindAs_function_type )( ::osg::Object const * ) const;
            
            PatchParameter_exposer.def( 
                "isSameKindAs"
                , isSameKindAs_function_type(&::osg::PatchParameter::isSameKindAs)
                , default_isSameKindAs_function_type(&PatchParameter_wrapper::default_isSameKindAs)
                , ( bp::arg("obj") ) );
        
        }
        { //::osg::PatchParameter::libraryName
        
            typedef char const * ( ::osg::PatchParameter::*libraryName_function_type )(  ) const;
            typedef char const * ( PatchParameter_wrapper::*default_libraryName_function_type )(  ) const;
            
            PatchParameter_exposer.def( 
                "libraryName"
                , libraryName_function_type(&::osg::PatchParameter::libraryName)
                , default_libraryName_function_type(&PatchParameter_wrapper::default_libraryName) );
        
        }
        { //::osg::PatchParameter::setPatchDefaultInnerLevel
        
            typedef void ( ::osg::PatchParameter::*setPatchDefaultInnerLevel_function_type )( ::osg::Vec2 const & ) ;
            
            PatchParameter_exposer.def( 
                "setPatchDefaultInnerLevel"
                , setPatchDefaultInnerLevel_function_type( &::osg::PatchParameter::setPatchDefaultInnerLevel )
                , ( bp::arg("level") )
                , " Set GL_PATCH_DEFAULT_INNER_LEVEL parameter." );
        
        }
        { //::osg::PatchParameter::setPatchDefaultOuterLevel
        
            typedef void ( ::osg::PatchParameter::*setPatchDefaultOuterLevel_function_type )( ::osg::Vec4 const & ) ;
            
            PatchParameter_exposer.def( 
                "setPatchDefaultOuterLevel"
                , setPatchDefaultOuterLevel_function_type( &::osg::PatchParameter::setPatchDefaultOuterLevel )
                , ( bp::arg("level") )
                , " Set GL_PATCH_DEFAULT_OUTER_LEVEL parameter." );
        
        }
        { //::osg::PatchParameter::setVertices
        
            typedef void ( ::osg::PatchParameter::*setVertices_function_type )( ::GLint ) ;
            
            PatchParameter_exposer.def( 
                "setVertices"
                , setVertices_function_type( &::osg::PatchParameter::setVertices )
                , ( bp::arg("vertices") )
                , " Set GL_PATCH_VERTICES parameter." );
        
        }
        { //::osg::StateAttribute::asTexture
        
            typedef ::osg::Texture * ( ::osg::StateAttribute::*asTexture_function_type )(  ) ;
            typedef ::osg::Texture * ( PatchParameter_wrapper::*default_asTexture_function_type )(  ) ;
            
            PatchParameter_exposer.def( 
                "asTexture"
                , asTexture_function_type(&::osg::StateAttribute::asTexture)
                , default_asTexture_function_type(&PatchParameter_wrapper::default_asTexture)
                , bp::return_internal_reference< >() );
        
        }
        { //::osg::StateAttribute::asTexture
        
            typedef ::osg::Texture const * ( ::osg::StateAttribute::*asTexture_function_type )(  ) const;
            typedef ::osg::Texture const * ( PatchParameter_wrapper::*default_asTexture_function_type )(  ) const;
            
            PatchParameter_exposer.def( 
                "asTexture"
                , asTexture_function_type(&::osg::StateAttribute::asTexture)
                , default_asTexture_function_type(&PatchParameter_wrapper::default_asTexture)
                , bp::return_internal_reference< >() );
        
        }
        { //::osg::StateAttribute::checkValidityOfAssociatedModes
        
            typedef bool ( ::osg::StateAttribute::*checkValidityOfAssociatedModes_function_type )( ::osg::State & ) const;
            typedef bool ( PatchParameter_wrapper::*default_checkValidityOfAssociatedModes_function_type )( ::osg::State & ) const;
            
            PatchParameter_exposer.def( 
                "checkValidityOfAssociatedModes"
                , checkValidityOfAssociatedModes_function_type(&::osg::StateAttribute::checkValidityOfAssociatedModes)
                , default_checkValidityOfAssociatedModes_function_type(&PatchParameter_wrapper::default_checkValidityOfAssociatedModes)
                , ( bp::arg("arg0") ) );
        
        }
        { //::osg::StateAttribute::compileGLObjects
        
            typedef void ( ::osg::StateAttribute::*compileGLObjects_function_type )( ::osg::State & ) const;
            typedef void ( PatchParameter_wrapper::*default_compileGLObjects_function_type )( ::osg::State & ) const;
            
            PatchParameter_exposer.def( 
                "compileGLObjects"
                , compileGLObjects_function_type(&::osg::StateAttribute::compileGLObjects)
                , default_compileGLObjects_function_type(&PatchParameter_wrapper::default_compileGLObjects)
                , ( bp::arg("arg0") ) );
        
        }
        { //::osg::StateAttribute::getMember
        
            typedef unsigned int ( ::osg::StateAttribute::*getMember_function_type )(  ) const;
            typedef unsigned int ( PatchParameter_wrapper::*default_getMember_function_type )(  ) const;
            
            PatchParameter_exposer.def( 
                "getMember"
                , getMember_function_type(&::osg::StateAttribute::getMember)
                , default_getMember_function_type(&PatchParameter_wrapper::default_getMember) );
        
        }
        { //::osg::StateAttribute::getModeUsage
        
            typedef bool ( ::osg::StateAttribute::*getModeUsage_function_type )( ::osg::StateAttribute::ModeUsage & ) const;
            typedef bool ( PatchParameter_wrapper::*default_getModeUsage_function_type )( ::osg::StateAttribute::ModeUsage & ) const;
            
            PatchParameter_exposer.def( 
                "getModeUsage"
                , getModeUsage_function_type(&::osg::StateAttribute::getModeUsage)
                , default_getModeUsage_function_type(&PatchParameter_wrapper::default_getModeUsage)
                , ( bp::arg("arg0") ) );
        
        }
        { //::osg::StateAttribute::isTextureAttribute
        
            typedef bool ( ::osg::StateAttribute::*isTextureAttribute_function_type )(  ) const;
            typedef bool ( PatchParameter_wrapper::*default_isTextureAttribute_function_type )(  ) const;
            
            PatchParameter_exposer.def( 
                "isTextureAttribute"
                , isTextureAttribute_function_type(&::osg::StateAttribute::isTextureAttribute)
                , default_isTextureAttribute_function_type(&PatchParameter_wrapper::default_isTextureAttribute) );
        
        }
        { //::osg::StateAttribute::resizeGLObjectBuffers
        
            typedef void ( ::osg::StateAttribute::*resizeGLObjectBuffers_function_type )( unsigned int ) ;
            typedef void ( PatchParameter_wrapper::*default_resizeGLObjectBuffers_function_type )( unsigned int ) ;
            
            PatchParameter_exposer.def( 
                "resizeGLObjectBuffers"
                , resizeGLObjectBuffers_function_type(&::osg::StateAttribute::resizeGLObjectBuffers)
                , default_resizeGLObjectBuffers_function_type(&PatchParameter_wrapper::default_resizeGLObjectBuffers)
                , ( bp::arg("arg0") ) );
        
        }
    }

}
