// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osg.h"
#include "wrap_referenced.h"
#include "RefBlock.pypp.hpp"

namespace bp = boost::python;

void register_RefBlock_class(){

    bp::class_< osg::RefBlock, bp::bases< osg::Referenced, OpenThreads::Block >, osg::ref_ptr< ::osg::RefBlock >, boost::noncopyable >( "RefBlock", bp::init< >() );

}
