// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osg.h"
#include "wrap_referenced.h"
#include "Shape.pypp.hpp"

namespace bp = boost::python;

struct Shape_wrapper : osg::Shape, bp::wrapper< osg::Shape > {

    virtual void accept( ::osg::ShapeVisitor & arg0 ){
        bp::override func_accept = this->get_override( "accept" );
        func_accept( boost::ref(arg0) );
    }

    virtual void accept( ::osg::ConstShapeVisitor & arg0 ) const {
        bp::override func_accept = this->get_override( "accept" );
        func_accept( boost::ref(arg0) );
    }

    virtual char const * className(  ) const  {
        if( bp::override func_className = this->get_override( "className" ) )
            return func_className(  );
        else{
            return this->osg::Shape::className(  );
        }
    }
    
    char const * default_className(  ) const  {
        return osg::Shape::className( );
    }

    virtual ::osg::Object * clone( ::osg::CopyOp const & arg0 ) const {
        bp::override func_clone = this->get_override( "clone" );
        return func_clone( boost::ref(arg0) );
    }

    virtual ::osg::Object * cloneType(  ) const {
        bp::override func_cloneType = this->get_override( "cloneType" );
        return func_cloneType(  );
    }

    virtual bool isSameKindAs( ::osg::Object const * obj ) const  {
        if( bp::override func_isSameKindAs = this->get_override( "isSameKindAs" ) )
            return func_isSameKindAs( boost::python::ptr(obj) );
        else{
            return this->osg::Shape::isSameKindAs( boost::python::ptr(obj) );
        }
    }
    
    bool default_isSameKindAs( ::osg::Object const * obj ) const  {
        return osg::Shape::isSameKindAs( boost::python::ptr(obj) );
    }

    virtual char const * libraryName(  ) const  {
        if( bp::override func_libraryName = this->get_override( "libraryName" ) )
            return func_libraryName(  );
        else{
            return this->osg::Shape::libraryName(  );
        }
    }
    
    char const * default_libraryName(  ) const  {
        return osg::Shape::libraryName( );
    }

};

void register_Shape_class(){

    bp::class_< Shape_wrapper, bp::bases< osg::Object >, osg::ref_ptr< ::osg::Shape >, boost::noncopyable >( "Shape", "\n Base class for all shape types.\n Shapes are used to either for culling and collision detection or\n to define the geometric shape of procedurally generate Geometry.\n", bp::no_init )    
        .def( 
            "accept"
            , bp::pure_virtual( (void ( ::osg::Shape::* )( ::osg::ShapeVisitor & ) )(&::osg::Shape::accept) )
            , ( bp::arg("arg0") )
            , "\n accept a non const shape visitor which can be used on non const shape objects.\n            Must be defined by derived classes.\n" )    
        .def( 
            "accept"
            , bp::pure_virtual( (void ( ::osg::Shape::* )( ::osg::ConstShapeVisitor & ) const)(&::osg::Shape::accept) )
            , ( bp::arg("arg0") )
            , "\n accept a const shape visitor which can be used on const shape objects.\n            Must be defined by derived classes.\n" )    
        .def( 
            "className"
            , (char const * ( ::osg::Shape::* )(  ) const)(&::osg::Shape::className)
            , (char const * ( Shape_wrapper::* )(  ) const)(&Shape_wrapper::default_className) )    
        .def( 
            "clone"
            , bp::pure_virtual( (::osg::Object * ( ::osg::Shape::* )( ::osg::CopyOp const & ) const)(&::osg::Shape::clone) )
            , ( bp::arg("arg0") )
            , bp::return_value_policy< bp::reference_existing_object >()
            , "\n Clone an attribute, with Object* return type.\n            Must be defined by derived classes.\n" )    
        .def( 
            "cloneType"
            , bp::pure_virtual( (::osg::Object * ( ::osg::Shape::* )(  ) const)(&::osg::Shape::cloneType) )
            , bp::return_value_policy< bp::reference_existing_object >()
            , "\n Clone the type of an attribute, with Object* return type.\n            Must be defined by derived classes.\n" )    
        .def( 
            "isSameKindAs"
            , (bool ( ::osg::Shape::* )( ::osg::Object const * ) const)(&::osg::Shape::isSameKindAs)
            , (bool ( Shape_wrapper::* )( ::osg::Object const * ) const)(&Shape_wrapper::default_isSameKindAs)
            , ( bp::arg("obj") ) )    
        .def( 
            "libraryName"
            , (char const * ( ::osg::Shape::* )(  ) const)(&::osg::Shape::libraryName)
            , (char const * ( Shape_wrapper::* )(  ) const)(&Shape_wrapper::default_libraryName) );

}
