// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osg.h"
#include "wrap_referenced.h"
#include "StandardNotifyHandler.pypp.hpp"

namespace bp = boost::python;

struct StandardNotifyHandler_wrapper : osg::StandardNotifyHandler, bp::wrapper< osg::StandardNotifyHandler > {

    StandardNotifyHandler_wrapper()
    : osg::StandardNotifyHandler()
      , bp::wrapper< osg::StandardNotifyHandler >(){
        // null constructor
        
    }

    virtual void notify( ::osg::NotifySeverity severity, char const * message ) {
        if( bp::override func_notify = this->get_override( "notify" ) )
            func_notify( severity, message );
        else{
            this->osg::StandardNotifyHandler::notify( severity, message );
        }
    }
    
    void default_notify( ::osg::NotifySeverity severity, char const * message ) {
        osg::StandardNotifyHandler::notify( severity, message );
    }

};

void register_StandardNotifyHandler_class(){

    bp::class_< StandardNotifyHandler_wrapper, bp::bases< osg::NotifyHandler >, osg::ref_ptr< ::osg::StandardNotifyHandler >, boost::noncopyable >( "StandardNotifyHandler", "\n Redirects notification stream to stderr (severity <= WARN) or stdout (severity > WARN).\n The fputs() function is used to write messages to standard files. Note that\n std::out and std::cerr streams are not used.\n aee setNotifyHandler\n" )    
        .def( 
            "notify"
            , (void ( ::osg::StandardNotifyHandler::* )( ::osg::NotifySeverity,char const * ) )(&::osg::StandardNotifyHandler::notify)
            , (void ( StandardNotifyHandler_wrapper::* )( ::osg::NotifySeverity,char const * ) )(&StandardNotifyHandler_wrapper::default_notify)
            , ( bp::arg("severity"), bp::arg("message") ) );

}
