// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osg.h"
#include "wrap_referenced.h"
#include "TexGen.pypp.hpp"

namespace bp = boost::python;

struct TexGen_wrapper : osg::TexGen, bp::wrapper< osg::TexGen > {

    TexGen_wrapper( )
    : osg::TexGen( )
      , bp::wrapper< osg::TexGen >(){
        // null constructor
    
    }

    virtual void apply( ::osg::State & state ) const  {
        if( bp::override func_apply = this->get_override( "apply" ) )
            func_apply( boost::ref(state) );
        else{
            this->osg::TexGen::apply( boost::ref(state) );
        }
    }
    
    void default_apply( ::osg::State & state ) const  {
        osg::TexGen::apply( boost::ref(state) );
    }

    virtual char const * className(  ) const  {
        if( bp::override func_className = this->get_override( "className" ) )
            return func_className(  );
        else{
            return this->osg::TexGen::className(  );
        }
    }
    
    char const * default_className(  ) const  {
        return osg::TexGen::className( );
    }

    virtual ::osg::Object * clone( ::osg::CopyOp const & copyop ) const  {
        if( bp::override func_clone = this->get_override( "clone" ) )
            return func_clone( boost::ref(copyop) );
        else{
            return this->osg::TexGen::clone( boost::ref(copyop) );
        }
    }
    
    ::osg::Object * default_clone( ::osg::CopyOp const & copyop ) const  {
        return osg::TexGen::clone( boost::ref(copyop) );
    }

    virtual ::osg::Object * cloneType(  ) const  {
        if( bp::override func_cloneType = this->get_override( "cloneType" ) )
            return func_cloneType(  );
        else{
            return this->osg::TexGen::cloneType(  );
        }
    }
    
    ::osg::Object * default_cloneType(  ) const  {
        return osg::TexGen::cloneType( );
    }

    virtual bool getModeUsage( ::osg::StateAttribute::ModeUsage & usage ) const  {
        if( bp::override func_getModeUsage = this->get_override( "getModeUsage" ) )
            return func_getModeUsage( boost::ref(usage) );
        else{
            return this->osg::TexGen::getModeUsage( boost::ref(usage) );
        }
    }
    
    bool default_getModeUsage( ::osg::StateAttribute::ModeUsage & usage ) const  {
        return osg::TexGen::getModeUsage( boost::ref(usage) );
    }

    virtual ::osg::StateAttribute::Type getType(  ) const  {
        if( bp::override func_getType = this->get_override( "getType" ) )
            return func_getType(  );
        else{
            return this->osg::TexGen::getType(  );
        }
    }
    
    ::osg::StateAttribute::Type default_getType(  ) const  {
        return osg::TexGen::getType( );
    }

    virtual bool isSameKindAs( ::osg::Object const * obj ) const  {
        if( bp::override func_isSameKindAs = this->get_override( "isSameKindAs" ) )
            return func_isSameKindAs( boost::python::ptr(obj) );
        else{
            return this->osg::TexGen::isSameKindAs( boost::python::ptr(obj) );
        }
    }
    
    bool default_isSameKindAs( ::osg::Object const * obj ) const  {
        return osg::TexGen::isSameKindAs( boost::python::ptr(obj) );
    }

    virtual bool isTextureAttribute(  ) const  {
        if( bp::override func_isTextureAttribute = this->get_override( "isTextureAttribute" ) )
            return func_isTextureAttribute(  );
        else{
            return this->osg::TexGen::isTextureAttribute(  );
        }
    }
    
    bool default_isTextureAttribute(  ) const  {
        return osg::TexGen::isTextureAttribute( );
    }

    virtual char const * libraryName(  ) const  {
        if( bp::override func_libraryName = this->get_override( "libraryName" ) )
            return func_libraryName(  );
        else{
            return this->osg::TexGen::libraryName(  );
        }
    }
    
    char const * default_libraryName(  ) const  {
        return osg::TexGen::libraryName( );
    }

    virtual ::osg::Texture * asTexture(  ) {
        if( bp::override func_asTexture = this->get_override( "asTexture" ) )
            return func_asTexture(  );
        else{
            return this->osg::StateAttribute::asTexture(  );
        }
    }
    
    ::osg::Texture * default_asTexture(  ) {
        return osg::StateAttribute::asTexture( );
    }

    virtual ::osg::Texture const * asTexture(  ) const  {
        if( bp::override func_asTexture = this->get_override( "asTexture" ) )
            return func_asTexture(  );
        else{
            return this->osg::StateAttribute::asTexture(  );
        }
    }
    
    ::osg::Texture const * default_asTexture(  ) const  {
        return osg::StateAttribute::asTexture( );
    }

    virtual bool checkValidityOfAssociatedModes( ::osg::State & arg0 ) const  {
        if( bp::override func_checkValidityOfAssociatedModes = this->get_override( "checkValidityOfAssociatedModes" ) )
            return func_checkValidityOfAssociatedModes( boost::ref(arg0) );
        else{
            return this->osg::StateAttribute::checkValidityOfAssociatedModes( boost::ref(arg0) );
        }
    }
    
    bool default_checkValidityOfAssociatedModes( ::osg::State & arg0 ) const  {
        return osg::StateAttribute::checkValidityOfAssociatedModes( boost::ref(arg0) );
    }

    virtual void compileGLObjects( ::osg::State & arg0 ) const  {
        if( bp::override func_compileGLObjects = this->get_override( "compileGLObjects" ) )
            func_compileGLObjects( boost::ref(arg0) );
        else{
            this->osg::StateAttribute::compileGLObjects( boost::ref(arg0) );
        }
    }
    
    void default_compileGLObjects( ::osg::State & arg0 ) const  {
        osg::StateAttribute::compileGLObjects( boost::ref(arg0) );
    }

    virtual unsigned int getMember(  ) const  {
        if( bp::override func_getMember = this->get_override( "getMember" ) )
            return func_getMember(  );
        else{
            return this->osg::StateAttribute::getMember(  );
        }
    }
    
    unsigned int default_getMember(  ) const  {
        return osg::StateAttribute::getMember( );
    }

    virtual void resizeGLObjectBuffers( unsigned int arg0 ) {
        if( bp::override func_resizeGLObjectBuffers = this->get_override( "resizeGLObjectBuffers" ) )
            func_resizeGLObjectBuffers( arg0 );
        else{
            this->osg::StateAttribute::resizeGLObjectBuffers( arg0 );
        }
    }
    
    void default_resizeGLObjectBuffers( unsigned int arg0 ) {
        osg::StateAttribute::resizeGLObjectBuffers( arg0 );
    }

};

void register_TexGen_class(){

    { //::osg::TexGen
        typedef bp::class_< TexGen_wrapper, bp::bases< osg::StateAttribute >, osg::ref_ptr< ::osg::TexGen >, boost::noncopyable > TexGen_exposer_t;
        TexGen_exposer_t TexGen_exposer = TexGen_exposer_t( "TexGen", "\n TexGen encapsulates the OpenGL glTexGen (texture coordinate generation)\n state.\n", bp::no_init );
        bp::scope TexGen_scope( TexGen_exposer );
        bp::enum_< osg::TexGen::Coord>("Coord")
            .value("S", osg::TexGen::S)
            .value("T", osg::TexGen::T)
            .value("R", osg::TexGen::R)
            .value("Q", osg::TexGen::Q)
            .export_values()
            ;
        bp::enum_< osg::TexGen::Mode>("Mode")
            .value("OBJECT_LINEAR", osg::TexGen::OBJECT_LINEAR)
            .value("EYE_LINEAR", osg::TexGen::EYE_LINEAR)
            .value("SPHERE_MAP", osg::TexGen::SPHERE_MAP)
            .value("NORMAL_MAP", osg::TexGen::NORMAL_MAP)
            .value("REFLECTION_MAP", osg::TexGen::REFLECTION_MAP)
            .export_values()
            ;
        TexGen_exposer.def( bp::init< >("\n TexGen encapsulates the OpenGL glTexGen (texture coordinate generation)\n state.\n") );
        { //::osg::TexGen::apply
        
            typedef void ( ::osg::TexGen::*apply_function_type )( ::osg::State & ) const;
            typedef void ( TexGen_wrapper::*default_apply_function_type )( ::osg::State & ) const;
            
            TexGen_exposer.def( 
                "apply"
                , apply_function_type(&::osg::TexGen::apply)
                , default_apply_function_type(&TexGen_wrapper::default_apply)
                , ( bp::arg("state") ) );
        
        }
        { //::osg::TexGen::className
        
            typedef char const * ( ::osg::TexGen::*className_function_type )(  ) const;
            typedef char const * ( TexGen_wrapper::*default_className_function_type )(  ) const;
            
            TexGen_exposer.def( 
                "className"
                , className_function_type(&::osg::TexGen::className)
                , default_className_function_type(&TexGen_wrapper::default_className) );
        
        }
        { //::osg::TexGen::clone
        
            typedef ::osg::Object * ( ::osg::TexGen::*clone_function_type )( ::osg::CopyOp const & ) const;
            typedef ::osg::Object * ( TexGen_wrapper::*default_clone_function_type )( ::osg::CopyOp const & ) const;
            
            TexGen_exposer.def( 
                "clone"
                , clone_function_type(&::osg::TexGen::clone)
                , default_clone_function_type(&TexGen_wrapper::default_clone)
                , ( bp::arg("copyop") )
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::osg::TexGen::cloneType
        
            typedef ::osg::Object * ( ::osg::TexGen::*cloneType_function_type )(  ) const;
            typedef ::osg::Object * ( TexGen_wrapper::*default_cloneType_function_type )(  ) const;
            
            TexGen_exposer.def( 
                "cloneType"
                , cloneType_function_type(&::osg::TexGen::cloneType)
                , default_cloneType_function_type(&TexGen_wrapper::default_cloneType)
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::osg::TexGen::getMode
        
            typedef ::osg::TexGen::Mode ( ::osg::TexGen::*getMode_function_type )(  ) const;
            
            TexGen_exposer.def( 
                "getMode"
                , getMode_function_type( &::osg::TexGen::getMode ) );
        
        }
        { //::osg::TexGen::getModeUsage
        
            typedef bool ( ::osg::TexGen::*getModeUsage_function_type )( ::osg::StateAttribute::ModeUsage & ) const;
            typedef bool ( TexGen_wrapper::*default_getModeUsage_function_type )( ::osg::StateAttribute::ModeUsage & ) const;
            
            TexGen_exposer.def( 
                "getModeUsage"
                , getModeUsage_function_type(&::osg::TexGen::getModeUsage)
                , default_getModeUsage_function_type(&TexGen_wrapper::default_getModeUsage)
                , ( bp::arg("usage") ) );
        
        }
        { //::osg::TexGen::getPlane
        
            typedef ::osg::Plane & ( ::osg::TexGen::*getPlane_function_type )( ::osg::TexGen::Coord ) ;
            
            TexGen_exposer.def( 
                "getPlane"
                , getPlane_function_type( &::osg::TexGen::getPlane )
                , ( bp::arg("which") )
                , bp::return_internal_reference< >() );
        
        }
        { //::osg::TexGen::getPlane
        
            typedef ::osg::Plane const & ( ::osg::TexGen::*getPlane_function_type )( ::osg::TexGen::Coord ) const;
            
            TexGen_exposer.def( 
                "getPlane"
                , getPlane_function_type( &::osg::TexGen::getPlane )
                , ( bp::arg("which") )
                , bp::return_internal_reference< >() );
        
        }
        { //::osg::TexGen::getType
        
            typedef ::osg::StateAttribute::Type ( ::osg::TexGen::*getType_function_type )(  ) const;
            typedef ::osg::StateAttribute::Type ( TexGen_wrapper::*default_getType_function_type )(  ) const;
            
            TexGen_exposer.def( 
                "getType"
                , getType_function_type(&::osg::TexGen::getType)
                , default_getType_function_type(&TexGen_wrapper::default_getType) );
        
        }
        { //::osg::TexGen::isSameKindAs
        
            typedef bool ( ::osg::TexGen::*isSameKindAs_function_type )( ::osg::Object const * ) const;
            typedef bool ( TexGen_wrapper::*default_isSameKindAs_function_type )( ::osg::Object const * ) const;
            
            TexGen_exposer.def( 
                "isSameKindAs"
                , isSameKindAs_function_type(&::osg::TexGen::isSameKindAs)
                , default_isSameKindAs_function_type(&TexGen_wrapper::default_isSameKindAs)
                , ( bp::arg("obj") ) );
        
        }
        { //::osg::TexGen::isTextureAttribute
        
            typedef bool ( ::osg::TexGen::*isTextureAttribute_function_type )(  ) const;
            typedef bool ( TexGen_wrapper::*default_isTextureAttribute_function_type )(  ) const;
            
            TexGen_exposer.def( 
                "isTextureAttribute"
                , isTextureAttribute_function_type(&::osg::TexGen::isTextureAttribute)
                , default_isTextureAttribute_function_type(&TexGen_wrapper::default_isTextureAttribute) );
        
        }
        { //::osg::TexGen::libraryName
        
            typedef char const * ( ::osg::TexGen::*libraryName_function_type )(  ) const;
            typedef char const * ( TexGen_wrapper::*default_libraryName_function_type )(  ) const;
            
            TexGen_exposer.def( 
                "libraryName"
                , libraryName_function_type(&::osg::TexGen::libraryName)
                , default_libraryName_function_type(&TexGen_wrapper::default_libraryName) );
        
        }
        { //::osg::TexGen::setMode
        
            typedef void ( ::osg::TexGen::*setMode_function_type )( ::osg::TexGen::Mode ) ;
            
            TexGen_exposer.def( 
                "setMode"
                , setMode_function_type( &::osg::TexGen::setMode )
                , ( bp::arg("mode") ) );
        
        }
        { //::osg::TexGen::setPlane
        
            typedef void ( ::osg::TexGen::*setPlane_function_type )( ::osg::TexGen::Coord,::osg::Plane const & ) ;
            
            TexGen_exposer.def( 
                "setPlane"
                , setPlane_function_type( &::osg::TexGen::setPlane )
                , ( bp::arg("which"), bp::arg("plane") ) );
        
        }
        { //::osg::TexGen::setPlanesFromMatrix
        
            typedef void ( ::osg::TexGen::*setPlanesFromMatrix_function_type )( ::osg::Matrixd const & ) ;
            
            TexGen_exposer.def( 
                "setPlanesFromMatrix"
                , setPlanesFromMatrix_function_type( &::osg::TexGen::setPlanesFromMatrix )
                , ( bp::arg("matrix") )
                , " Set the tex gen planes from specified matrix.\n Typical usage would be to pass in a projection\n matrix to set up projective texturing." );
        
        }
        { //::osg::StateAttribute::asTexture
        
            typedef ::osg::Texture * ( ::osg::StateAttribute::*asTexture_function_type )(  ) ;
            typedef ::osg::Texture * ( TexGen_wrapper::*default_asTexture_function_type )(  ) ;
            
            TexGen_exposer.def( 
                "asTexture"
                , asTexture_function_type(&::osg::StateAttribute::asTexture)
                , default_asTexture_function_type(&TexGen_wrapper::default_asTexture)
                , bp::return_internal_reference< >() );
        
        }
        { //::osg::StateAttribute::asTexture
        
            typedef ::osg::Texture const * ( ::osg::StateAttribute::*asTexture_function_type )(  ) const;
            typedef ::osg::Texture const * ( TexGen_wrapper::*default_asTexture_function_type )(  ) const;
            
            TexGen_exposer.def( 
                "asTexture"
                , asTexture_function_type(&::osg::StateAttribute::asTexture)
                , default_asTexture_function_type(&TexGen_wrapper::default_asTexture)
                , bp::return_internal_reference< >() );
        
        }
        { //::osg::StateAttribute::checkValidityOfAssociatedModes
        
            typedef bool ( ::osg::StateAttribute::*checkValidityOfAssociatedModes_function_type )( ::osg::State & ) const;
            typedef bool ( TexGen_wrapper::*default_checkValidityOfAssociatedModes_function_type )( ::osg::State & ) const;
            
            TexGen_exposer.def( 
                "checkValidityOfAssociatedModes"
                , checkValidityOfAssociatedModes_function_type(&::osg::StateAttribute::checkValidityOfAssociatedModes)
                , default_checkValidityOfAssociatedModes_function_type(&TexGen_wrapper::default_checkValidityOfAssociatedModes)
                , ( bp::arg("arg0") ) );
        
        }
        { //::osg::StateAttribute::compileGLObjects
        
            typedef void ( ::osg::StateAttribute::*compileGLObjects_function_type )( ::osg::State & ) const;
            typedef void ( TexGen_wrapper::*default_compileGLObjects_function_type )( ::osg::State & ) const;
            
            TexGen_exposer.def( 
                "compileGLObjects"
                , compileGLObjects_function_type(&::osg::StateAttribute::compileGLObjects)
                , default_compileGLObjects_function_type(&TexGen_wrapper::default_compileGLObjects)
                , ( bp::arg("arg0") ) );
        
        }
        { //::osg::StateAttribute::getMember
        
            typedef unsigned int ( ::osg::StateAttribute::*getMember_function_type )(  ) const;
            typedef unsigned int ( TexGen_wrapper::*default_getMember_function_type )(  ) const;
            
            TexGen_exposer.def( 
                "getMember"
                , getMember_function_type(&::osg::StateAttribute::getMember)
                , default_getMember_function_type(&TexGen_wrapper::default_getMember) );
        
        }
        { //::osg::StateAttribute::resizeGLObjectBuffers
        
            typedef void ( ::osg::StateAttribute::*resizeGLObjectBuffers_function_type )( unsigned int ) ;
            typedef void ( TexGen_wrapper::*default_resizeGLObjectBuffers_function_type )( unsigned int ) ;
            
            TexGen_exposer.def( 
                "resizeGLObjectBuffers"
                , resizeGLObjectBuffers_function_type(&::osg::StateAttribute::resizeGLObjectBuffers)
                , default_resizeGLObjectBuffers_function_type(&TexGen_wrapper::default_resizeGLObjectBuffers)
                , ( bp::arg("arg0") ) );
        
        }
    }

}
