// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osg.h"
#include "wrap_referenced.h"
#include "VertexBufferObject.pypp.hpp"

namespace bp = boost::python;

struct VertexBufferObject_wrapper : osg::VertexBufferObject, bp::wrapper< osg::VertexBufferObject > {

    VertexBufferObject_wrapper( )
    : osg::VertexBufferObject( )
      , bp::wrapper< osg::VertexBufferObject >(){
        // null constructor
    
    }

    virtual char const * className(  ) const  {
        if( bp::override func_className = this->get_override( "className" ) )
            return func_className(  );
        else{
            return this->osg::VertexBufferObject::className(  );
        }
    }
    
    char const * default_className(  ) const  {
        return osg::VertexBufferObject::className( );
    }

    virtual ::osg::Object * clone( ::osg::CopyOp const & copyop ) const  {
        if( bp::override func_clone = this->get_override( "clone" ) )
            return func_clone( boost::ref(copyop) );
        else{
            return this->osg::VertexBufferObject::clone( boost::ref(copyop) );
        }
    }
    
    ::osg::Object * default_clone( ::osg::CopyOp const & copyop ) const  {
        return osg::VertexBufferObject::clone( boost::ref(copyop) );
    }

    virtual ::osg::Object * cloneType(  ) const  {
        if( bp::override func_cloneType = this->get_override( "cloneType" ) )
            return func_cloneType(  );
        else{
            return this->osg::VertexBufferObject::cloneType(  );
        }
    }
    
    ::osg::Object * default_cloneType(  ) const  {
        return osg::VertexBufferObject::cloneType( );
    }

    virtual bool isSameKindAs( ::osg::Object const * obj ) const  {
        if( bp::override func_isSameKindAs = this->get_override( "isSameKindAs" ) )
            return func_isSameKindAs( boost::python::ptr(obj) );
        else{
            return this->osg::VertexBufferObject::isSameKindAs( boost::python::ptr(obj) );
        }
    }
    
    bool default_isSameKindAs( ::osg::Object const * obj ) const  {
        return osg::VertexBufferObject::isSameKindAs( boost::python::ptr(obj) );
    }

    virtual char const * libraryName(  ) const  {
        if( bp::override func_libraryName = this->get_override( "libraryName" ) )
            return func_libraryName(  );
        else{
            return this->osg::VertexBufferObject::libraryName(  );
        }
    }
    
    char const * default_libraryName(  ) const  {
        return osg::VertexBufferObject::libraryName( );
    }

    virtual void resizeGLObjectBuffers( unsigned int maxSize ) {
        if( bp::override func_resizeGLObjectBuffers = this->get_override( "resizeGLObjectBuffers" ) )
            func_resizeGLObjectBuffers( maxSize );
        else{
            this->osg::BufferObject::resizeGLObjectBuffers( maxSize );
        }
    }
    
    void default_resizeGLObjectBuffers( unsigned int maxSize ) {
        osg::BufferObject::resizeGLObjectBuffers( maxSize );
    }

};

void register_VertexBufferObject_class(){

    bp::class_< VertexBufferObject_wrapper, bp::bases< osg::BufferObject >, osg::ref_ptr< ::osg::VertexBufferObject >, boost::noncopyable >( "VertexBufferObject", bp::no_init )    
        .def( bp::init< >() )    
        .def( 
            "addArray"
            , (unsigned int ( ::osg::VertexBufferObject::* )( ::osg::Array * ) )( &::osg::VertexBufferObject::addArray )
            , ( bp::arg("array") ) )    
        .def( 
            "className"
            , (char const * ( ::osg::VertexBufferObject::* )(  ) const)(&::osg::VertexBufferObject::className)
            , (char const * ( VertexBufferObject_wrapper::* )(  ) const)(&VertexBufferObject_wrapper::default_className) )    
        .def( 
            "clone"
            , (::osg::Object * ( ::osg::VertexBufferObject::* )( ::osg::CopyOp const & ) const)(&::osg::VertexBufferObject::clone)
            , (::osg::Object * ( VertexBufferObject_wrapper::* )( ::osg::CopyOp const & ) const)(&VertexBufferObject_wrapper::default_clone)
            , ( bp::arg("copyop") )
            , bp::return_value_policy< bp::reference_existing_object >() )    
        .def( 
            "cloneType"
            , (::osg::Object * ( ::osg::VertexBufferObject::* )(  ) const)(&::osg::VertexBufferObject::cloneType)
            , (::osg::Object * ( VertexBufferObject_wrapper::* )(  ) const)(&VertexBufferObject_wrapper::default_cloneType)
            , bp::return_value_policy< bp::reference_existing_object >() )    
        .def( 
            "getArray"
            , (::osg::Array * ( ::osg::VertexBufferObject::* )( unsigned int ) )( &::osg::VertexBufferObject::getArray )
            , ( bp::arg("i") )
            , bp::return_internal_reference< >() )    
        .def( 
            "getArray"
            , (::osg::Array const * ( ::osg::VertexBufferObject::* )( unsigned int ) const)( &::osg::VertexBufferObject::getArray )
            , ( bp::arg("i") )
            , bp::return_internal_reference< >() )    
        .def( 
            "isSameKindAs"
            , (bool ( ::osg::VertexBufferObject::* )( ::osg::Object const * ) const)(&::osg::VertexBufferObject::isSameKindAs)
            , (bool ( VertexBufferObject_wrapper::* )( ::osg::Object const * ) const)(&VertexBufferObject_wrapper::default_isSameKindAs)
            , ( bp::arg("obj") ) )    
        .def( 
            "libraryName"
            , (char const * ( ::osg::VertexBufferObject::* )(  ) const)(&::osg::VertexBufferObject::libraryName)
            , (char const * ( VertexBufferObject_wrapper::* )(  ) const)(&VertexBufferObject_wrapper::default_libraryName) )    
        .def( 
            "removeArray"
            , (void ( ::osg::VertexBufferObject::* )( ::osg::Array * ) )( &::osg::VertexBufferObject::removeArray )
            , ( bp::arg("array") ) )    
        .def( 
            "setArray"
            , (void ( ::osg::VertexBufferObject::* )( unsigned int,::osg::Array * ) )( &::osg::VertexBufferObject::setArray )
            , ( bp::arg("i"), bp::arg("array") ) )    
        .def( 
            "resizeGLObjectBuffers"
            , (void ( ::osg::BufferObject::* )( unsigned int ) )(&::osg::BufferObject::resizeGLObjectBuffers)
            , (void ( VertexBufferObject_wrapper::* )( unsigned int ) )(&VertexBufferObject_wrapper::default_resizeGLObjectBuffers)
            , ( bp::arg("maxSize") ) );

}
