// This file has been generated by Py++.

#include "boost/python.hpp"

#include "__call_policies.pypp.hpp"

#include "__convenience.pypp.hpp"

#include "indexing_suite/container_suite.hpp"

#include "indexing_suite/vector.hpp"

#include "indexing_suite/list.hpp"

#include "wrap_osgWidget.h"

#include "Box.pypp.hpp"

#include "Browser.pypp.hpp"

#include "BrowserImage.pypp.hpp"

#include "BrowserManager.pypp.hpp"

#include "Callback.pypp.hpp"

#include "CallbackInterface.pypp.hpp"

#include "CameraSwitchHandler.pypp.hpp"

#include "Canvas.pypp.hpp"

#include "Event.pypp.hpp"

#include "EventInterface.pypp.hpp"

#include "Frame.pypp.hpp"

#include "GeometryHints.pypp.hpp"

#include "Input.pypp.hpp"

#include "KeyboardHandler.pypp.hpp"

#include "Label.pypp.hpp"

#include "LuaEngine.pypp.hpp"

#include "MouseHandler.pypp.hpp"

#include "NotifyWidget.pypp.hpp"

#include "NullWidget.pypp.hpp"

#include "PdfImage.pypp.hpp"

#include "PdfReader.pypp.hpp"

#include "PythonEngine.pypp.hpp"

#include "ResizeHandler.pypp.hpp"

#include "ScriptEngine.pypp.hpp"

#include "Style.pypp.hpp"

#include "StyleInterface.pypp.hpp"

#include "StyleManager.pypp.hpp"

#include "Table.pypp.hpp"

#include "UIObjectParent_Widget_Vector.pypp.hpp"

#include "UIObjectParent_Window_Vector.pypp.hpp"

#include "UIObjectParent_less__osgWidget_scope_Widget__greater_.pypp.hpp"

#include "UIObjectParent_less__osgWidget_scope_Window__greater_.pypp.hpp"

#include "VncClient.pypp.hpp"

#include "VncImage.pypp.hpp"

#include "Widget.pypp.hpp"

#include "Window.pypp.hpp"

#include "WindowList.pypp.hpp"

#include "WindowManager.pypp.hpp"

#include "_osgWidget_enumerations.pypp.hpp"

#include "_osgWidget_free_functions.pypp.hpp"

#include "_osgWidget_global_variables.pypp.hpp"

#include "list_less__osg_scope_observer_ptr_less_osgWidget_scope_Widget_greater___greater_.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(_osgWidget){
    register_enumerations();

    register_UIObjectParent_Window_Vector_class();

    register_UIObjectParent_Widget_Vector_class();

    register_WindowList_class();

    register_list_less__osg_scope_observer_ptr_less_osgWidget_scope_Widget_greater___greater__class();

    register_EventInterface_class();

    register_StyleInterface_class();

    register_UIObjectParent_less__osgWidget_scope_Widget__greater__class();

    register_Widget_class();

    register_Window_class();

    register_Box_class();

    register_GeometryHints_class();

    register_Browser_class();

    register_BrowserImage_class();

    register_BrowserManager_class();

    register_Callback_class();

    register_CallbackInterface_class();

    register_CameraSwitchHandler_class();

    register_Canvas_class();

    register_Event_class();

    register_Table_class();

    register_Frame_class();

    register_Label_class();

    register_Input_class();

    register_KeyboardHandler_class();

    register_ScriptEngine_class();

    register_UIObjectParent_less__osgWidget_scope_Window__greater__class();

    register_WindowManager_class();

    register_LuaEngine_class();

    register_MouseHandler_class();

    register_NotifyWidget_class();

    register_NullWidget_class();

    register_PdfImage_class();

    register_PdfReader_class();

    register_PythonEngine_class();

    register_ResizeHandler_class();

    register_Style_class();

    register_StyleManager_class();

    register_VncClient_class();

    register_VncImage_class();

    register_global_variables();

    register_free_functions();
}

