// This file has been generated by Py++.

#ifndef UIObjectParent_Window_Vector_hpp__pyplusplus_wrapper
#define UIObjectParent_Window_Vector_hpp__pyplusplus_wrapper

void register_UIObjectParent_Window_Vector_class();

#endif//UIObjectParent_Window_Vector_hpp__pyplusplus_wrapper
