// This file has been generated by Py++.

#include "boost/python.hpp"

#include "__convenience.pypp.hpp"

#include "__call_policies.pypp.hpp"

#include "indexing_suite/container_suite.hpp"

#include "indexing_suite/vector.hpp"

#include "indexing_suite/list.hpp"

#include "wrap_osgViewer.h"

#include "Cameras.pypp.hpp"

#include "CompositeViewer.pypp.hpp"

#include "DepthPartitionSettings.pypp.hpp"

#include "Devices.pypp.hpp"

#include "EventHandlers.pypp.hpp"

#include "GraphicsWindow.pypp.hpp"

#include "GraphicsWindowEmbedded.pypp.hpp"

#include "GraphicsWindowFunctionProxy.pypp.hpp"

#include "HelpHandler.pypp.hpp"

#include "InteractiveImageHandler.pypp.hpp"

#include "Keystone.pypp.hpp"

#include "KeystoneHandler.pypp.hpp"

#include "LODScaleHandler.pypp.hpp"

#include "OpenGLQuerySupport.pypp.hpp"

#include "RecordCameraPathHandler.pypp.hpp"

#include "Renderer.pypp.hpp"

#include "Scene.pypp.hpp"

#include "ScreenCaptureHandler.pypp.hpp"

#include "StatsHandler.pypp.hpp"

#include "ThreadingHandler.pypp.hpp"

#include "ToggleSyncToVBlankHandler.pypp.hpp"

#include "View.pypp.hpp"

#include "ViewConfig.pypp.hpp"

#include "Viewer.pypp.hpp"

#include "ViewerBase.pypp.hpp"

#include "WindowSizeHandler.pypp.hpp"

#include "_osgViewer_free_functions.pypp.hpp"

#include "list_less__osgViewer_scope_View_ptr___greater_.pypp.hpp"

#include "vector_less__OpenThreads_scope_Thread_ptr___greater_.pypp.hpp"

#include "vector_less__osgViewer_scope_GraphicsWindow_ptr___greater_.pypp.hpp"

#include "vector_less__osgViewer_scope_Scene_ptr___greater_.pypp.hpp"

#include "vector_less__osgViewer_scope_View_ptr___greater_.pypp.hpp"

#include "vector_less__osg_scope_OperationThread_ptr___greater_.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(_osgViewer){
    register_vector_less__osgViewer_scope_View_ptr___greater__class();

    register_vector_less__osgViewer_scope_Scene_ptr___greater__class();

    register_vector_less__osgViewer_scope_GraphicsWindow_ptr___greater__class();

    register_Devices_class();

    register_vector_less__osg_scope_OperationThread_ptr___greater__class();

    register_Cameras_class();

    register_vector_less__OpenThreads_scope_Thread_ptr___greater__class();

    register_list_less__osgViewer_scope_View_ptr___greater__class();

    register_EventHandlers_class();

    register_ViewerBase_class();

    register_CompositeViewer_class();

    register_DepthPartitionSettings_class();

    register_GraphicsWindow_class();

    register_GraphicsWindowEmbedded_class();

    register_GraphicsWindowFunctionProxy_class();

    register_HelpHandler_class();

    register_InteractiveImageHandler_class();

    register_Keystone_class();

    register_KeystoneHandler_class();

    register_LODScaleHandler_class();

    register_OpenGLQuerySupport_class();

    register_RecordCameraPathHandler_class();

    register_Renderer_class();

    register_Scene_class();

    register_ScreenCaptureHandler_class();

    register_StatsHandler_class();

    register_ThreadingHandler_class();

    register_ToggleSyncToVBlankHandler_class();

    register_View_class();

    register_ViewConfig_class();

    register_Viewer_class();

    register_WindowSizeHandler_class();

    register_free_functions();
}

