// This file has been generated by Py++.

#include "boost/python.hpp"
#include "wrap_osgFX.h"
#include "wrap_referenced.h"
#include "Registry.pypp.hpp"

namespace bp = boost::python;

void register_Registry_class(){

    { //::osgFX::Registry
        typedef bp::class_< osgFX::Registry, bp::bases< ::osg::Referenced >, osg::ref_ptr< osgFX::Registry >, boost::noncopyable > Registry_exposer_t;
        Registry_exposer_t Registry_exposer = Registry_exposer_t( "Registry", bp::no_init );
        bp::scope Registry_scope( Registry_exposer );
        { //::osgFX::Registry::Proxy
            typedef bp::class_< osgFX::Registry::Proxy > Proxy_exposer_t;
            Proxy_exposer_t Proxy_exposer = Proxy_exposer_t( "Proxy", bp::init< osgFX::Effect const * >(( bp::arg("effect") )) );
            bp::scope Proxy_scope( Proxy_exposer );
            bp::implicitly_convertible< osgFX::Effect const *, osgFX::Registry::Proxy >();
        }
        { //::osgFX::Registry::getEffectMap
        
            typedef ::std::map< std::string, osg::ref_ptr<osgFX::Effect const> > const & ( ::osgFX::Registry::*getEffectMap_function_type )(  ) const;
            
            Registry_exposer.def( 
                "getEffectMap"
                , getEffectMap_function_type( &::osgFX::Registry::getEffectMap )
                , bp::return_internal_reference< >() );
        
        }
        { //::osgFX::Registry::instance
        
            typedef ::osgFX::Registry * ( *instance_function_type )(  );
            
            Registry_exposer.def( 
                "instance"
                , instance_function_type( &::osgFX::Registry::instance )
                , bp::return_internal_reference< >() );
        
        }
        { //::osgFX::Registry::registerEffect
        
            typedef void ( ::osgFX::Registry::*registerEffect_function_type )( ::osgFX::Effect const * ) ;
            
            Registry_exposer.def( 
                "registerEffect"
                , registerEffect_function_type( &::osgFX::Registry::registerEffect )
                , ( bp::arg("effect") ) );
        
        }
        { //::osgFX::Registry::removeEffect
        
            typedef void ( ::osgFX::Registry::*removeEffect_function_type )( ::osgFX::Effect const * ) ;
            
            Registry_exposer.def( 
                "removeEffect"
                , removeEffect_function_type( &::osgFX::Registry::removeEffect )
                , ( bp::arg("effect") ) );
        
        }
        Registry_exposer.staticmethod( "instance" );
    }

}
