// This file has been generated by Py++.

#include "boost/python.hpp"

#include "indexing_suite/value_traits.hpp"

#include "indexing_suite/container_suite.hpp"

#include "indexing_suite/vector.hpp"

#include "wrap_osgSim.h"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/AzimElevationSector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/AzimRange.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/AzimSector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/BlinkSequence.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/ColorRange.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/ConeSector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/DOFTransform.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/DatabaseCacheReadCallback.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/DirectionalSector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/ElevationRange.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/ElevationSector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/ElevationSlice.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/HeightAboveTerrain.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/Impostor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/ImpostorSprite.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/ImpostorSpriteManager.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/InsertImpostorsVisitor.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/LightPoint.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/LightPointList.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/LightPointNode.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/LightPointSystem.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/LineOfSight.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/MultiSwitch.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/ObjectRecordData.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/OverlayNode.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/ScalarBar.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/ScalarsToColors.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/Sector.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/SequenceGroup.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/ShapeAttribute.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/ShapeAttributeList.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/SphereSegment.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/VisibilityGroup.pypp.hpp"

#include "/home/cmbruns/git/osgpyplusplus/src/modules/osgSim/generated_code/vector_less__osg_scope_ref_ptr_less_osgSim_scope_ImpostorSprite_greater___greater_.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(_osgSim){
    register_LightPointList_class();

    register_vector_less__osg_scope_ref_ptr_less_osgSim_scope_ImpostorSprite_greater___greater__class();

    register_AzimRange_class();

    register_ElevationRange_class();

    register_Sector_class();

    register_AzimElevationSector_class();

    register_AzimSector_class();

    register_BlinkSequence_class();

    register_ScalarsToColors_class();

    register_ColorRange_class();

    register_ConeSector_class();

    register_DOFTransform_class();

    register_DatabaseCacheReadCallback_class();

    register_DirectionalSector_class();

    register_ElevationSector_class();

    register_ElevationSlice_class();

    register_HeightAboveTerrain_class();

    register_Impostor_class();

    register_ImpostorSprite_class();

    register_ImpostorSpriteManager_class();

    register_InsertImpostorsVisitor_class();

    register_LightPoint_class();

    register_LightPointNode_class();

    register_LightPointSystem_class();

    register_LineOfSight_class();

    register_MultiSwitch_class();

    register_ObjectRecordData_class();

    register_OverlayNode_class();

    register_ScalarBar_class();

    register_SequenceGroup_class();

    register_ShapeAttribute_class();

    register_ShapeAttributeList_class();

    register_SphereSegment_class();

    register_VisibilityGroup_class();
}

